local _, OSG = ...

-- Settings that duplicate a feature of another tracked add-on. Each must stay off
-- while every add-on in `when` is loaded. `when[1]` is the add-on that owns the setting;
-- its adapter is hooked only when that add-on is loaded. The policy changes here and in
-- readme.md, never in game.
OSG.policy = {
  {
    id = "leatrix.minimap",
    adapter = "LeatrixPlus",
    key = "MinimapModder",
    label = "Leatrix Plus: Enhance minimap",
    when = { "Leatrix_Plus", "ForeverUI" },
    reason = "ForeverUI's Minimap module already squares and styles the minimap.",
    needsReload = true,
  },
  {
    id = "leatrix.editbox",
    adapter = "LeatrixPlus",
    key = "MoveChatEditBoxToTop",
    label = "Leatrix Plus: Move editbox to top",
    when = { "Leatrix_Plus", "ForeverUI" },
    reason = "ForeverUI's chat setting \"Where you type\" places the edit box.",
    needsReload = true,
  },
  {
    id = "leatrix.chatfont",
    adapter = "LeatrixPlus",
    key = "SetChatFontSize",
    label = "Leatrix Plus: Set chat font size",
    when = { "Leatrix_Plus", "ForeverUI" },
    reason = "ForeverUI sets the chat font size; Leatrix's size overrides it after login.",
    needsReload = true,
  },
  {
    id = "leatrix.autoquests",
    adapter = "LeatrixPlus",
    key = "AutomateQuests",
    label = "Leatrix Plus: Automate quests",
    when = { "Leatrix_Plus", "RXPGuides" },
    reason = "RestedXP Guide accepts and turns in the quests on its route; Leatrix would also take quests the route skips.",
  },
  {
    id = "leatrix.autogossip",
    adapter = "LeatrixPlus",
    key = "AutomateGossip",
    label = "Leatrix Plus: Automate gossip",
    when = { "Leatrix_Plus", "RXPGuides" },
    reason = "RestedXP Guide picks gossip options for its route.",
  },
  {
    id = "fui.questforever",
    adapter = "ForeverUI",
    key = "QuestForeverModule",
    label = "ForeverUI: QuestForever",
    when = { "ForeverUI", "RXPGuides" },
    reason = "RestedXP Guide draws its route on the map and minimap; QuestForever pins every quest you could take.",
  },
  {
    id = "fui.guideonaccept",
    adapter = "ForeverUI",
    key = "QuestGuideOnAccept",
    label = "ForeverUI: Open the quest guide on accept",
    when = { "ForeverUI", "RXPGuides" },
    reason = "RestedXP Guide accepts quests for you and shows its own steps, so the guide would open at almost every quest giver.",
  },
  {
    id = "fui.arrow",
    adapter = "ForeverUI",
    key = "ArrowModule",
    label = "ForeverUI: Waypoint arrow",
    when = { "ForeverUI", "RXPGuides" },
    reason = "RestedXP Guide has its own arrow to the next step.",
  },
  {
    id = "fui.selljunk",
    adapter = "ForeverUI",
    key = "LootSellJunk",
    label = "ForeverUI: Sell junk at vendors",
    when = { "ForeverUI", "Leatrix_Plus" },
    reason = "Leatrix Plus \"Sell junk automatically\" sells grey items.",
  },
  {
    id = "leatrix.flighttimes",
    adapter = "LeatrixPlus",
    key = "ShowFlightTimes",
    label = "Leatrix Plus: Show flight times",
    when = { "Leatrix_Plus", "RXPGuides" },
    reason = "RestedXP Guide shows flight times on the flight map and a flight progress bar.",
    needsReload = true,
  },
  {
    id = "rxp.selljunk",
    adapter = "RestedXP",
    key = "AutoSellJunk",
    label = "RestedXP: Auto Sell Junk",
    when = { "RXPGuides", "Leatrix_Plus" },
    reason = "Leatrix Plus \"Sell junk automatically\" sells grey items.",
  },
  {
    id = "rxp.talentguides",
    adapter = "RestedXP",
    key = "TalentGuides",
    label = "RestedXP: Enable Talents Guides",
    when = { "RXPGuides", "TalentsForeverBook" },
    reason = "Talents Forever plans talents for Forever's talent window.",
    needsReload = true,
  },
  {
    id = "rxp.upgradetooltip",
    adapter = "RestedXP",
    key = "UpgradeTooltip",
    label = "RestedXP: Item upgrade tooltips (\"Disable Tooltips\" unticked)",
    when = { "RXPGuides", "ForeverUI" },
    reason = "ForeverUI's Loot module marks upgrades in tooltips and bags. RestedXP's quest reward advice stays on.",
  },
  {
    id = "rxp.nameplatedistance",
    adapter = "RestedXP",
    key = "MaxNameplateDistance",
    label = "RestedXP: Maximize Nameplate Distance",
    when = { "RXPGuides", "ForeverUI" },
    reason = "It sets nameplate range to 41 at every loading screen, overriding ForeverUI's nameplate distance.",
    needsReload = true,
  },
}
