local _, OSG = ...

OSG.policy = {
  {
    id = "leatrix.minimap",
    adapter = "LeatrixPlus",
    key = "MinimapModder",
    label = "Leatrix Plus: Enhance minimap",
    when = { "Leatrix_Plus", "ForeverUI" },
    reason = "ForeverUI's Minimap module already squares and styles the minimap.",
    needsReload = true,
  },
  {
    id = "leatrix.editbox",
    adapter = "LeatrixPlus",
    key = "MoveChatEditBoxToTop",
    label = "Leatrix Plus: Move editbox to top",
    when = { "Leatrix_Plus", "ForeverUI" },
    reason = "ForeverUI's chat setting \"Where you type\" places the edit box.",
    needsReload = true,
  },
  {
    id = "leatrix.chatfont",
    adapter = "LeatrixPlus",
    key = "SetChatFontSize",
    label = "Leatrix Plus: Set chat font size",
    when = { "Leatrix_Plus", "ForeverUI" },
    reason = "ForeverUI sets the chat font size; Leatrix's size overrides it after login.",
    needsReload = true,
  },
  {
    id = "rxp.autoquests",
    adapter = "RestedXP",
    key = "QuestAutomation",
    label = "RestedXP: Quest auto accept/turn in",
    when = { "RXPGuides", "Leatrix_Plus" },
    reason = "Leatrix Plus accepts and turns in quests broadly, including quests outside the active guide.",
  },
  {
    id = "rxp.autogossip",
    adapter = "RestedXP",
    key = "GossipAutomation",
    label = "RestedXP: Gossip automation",
    when = { "RXPGuides", "Leatrix_Plus" },
    reason = "Leatrix Plus handles gossip for quest interactions.",
  },
  {
    id = "rxp.questrewards",
    adapter = "RestedXP",
    key = "QuestRewardAutomation",
    label = "RestedXP: Quest auto rewards",
    when = { "RXPGuides", "Leatrix_Plus" },
    reason = "Leatrix Plus owns quest turn-ins; RestedXP must not claim guide-selected rewards.",
  },
  {
    id = "rxp.questchoices",
    adapter = "RestedXP",
    key = "QuestChoiceAutomation",
    label = "RestedXP: Quest Reward Automation",
    when = { "RXPGuides", "Leatrix_Plus" },
    reason = "Leatrix Plus owns quest turn-ins; RestedXP must not claim calculated rewards.",
  },
  {
    id = "fui.questforever",
    adapter = "ForeverUI",
    key = "QuestForeverModule",
    label = "ForeverUI: QuestForever",
    when = { "ForeverUI", "RXPGuides" },
    reason = "RestedXP Guide draws its route on the map and minimap; QuestForever pins every quest you could take.",
  },
  {
    id = "fui.guideonaccept",
    adapter = "ForeverUI",
    key = "QuestGuideOnAccept",
    label = "ForeverUI: Open the quest guide on accept",
    when = { "ForeverUI", "RXPGuides" },
    reason = "Leatrix Plus accepts quests automatically and RestedXP shows the guide steps, so ForeverUI's guide would open at almost every quest giver.",
  },
  {
    id = "fui.arrow",
    adapter = "ForeverUI",
    key = "ArrowModule",
    label = "ForeverUI: Waypoint arrow",
    when = { "ForeverUI", "RXPGuides" },
    reason = "RestedXP Guide has its own arrow to the next step.",
  },
  {
    id = "fui.selljunk",
    adapter = "ForeverUI",
    key = "LootSellJunk",
    label = "ForeverUI: Sell junk at vendors",
    when = { "ForeverUI", "Leatrix_Plus" },
    reason = "Leatrix Plus \"Sell junk automatically\" sells grey items.",
  },
  {
    id = "leatrix.flighttimes",
    adapter = "LeatrixPlus",
    key = "ShowFlightTimes",
    label = "Leatrix Plus: Show flight times",
    when = { "Leatrix_Plus", "RXPGuides" },
    reason = "RestedXP Guide shows flight times on the flight map and a flight progress bar.",
    needsReload = true,
  },
  {
    id = "rxp.selljunk",
    adapter = "RestedXP",
    key = "AutoSellJunk",
    label = "RestedXP: Auto Sell Junk",
    when = { "RXPGuides", "Leatrix_Plus" },
    reason = "Leatrix Plus \"Sell junk automatically\" sells grey items.",
  },
  {
    id = "rxp.talentguides",
    adapter = "RestedXP",
    key = "TalentGuides",
    label = "RestedXP: Enable Talents Guides",
    when = { "RXPGuides", "TalentsForeverBook" },
    reason = "Talents Forever plans talents for Forever's talent window.",
    needsReload = true,
  },
  {
    id = "rxp.upgradetooltip",
    adapter = "RestedXP",
    key = "UpgradeTooltip",
    label = "RestedXP: Item upgrade tooltips (\"Disable Tooltips\" unticked)",
    when = { "RXPGuides", "ForeverUI" },
    reason = "ForeverUI's Loot module marks upgrades in tooltips and bags. RestedXP's quest reward advice stays on.",
  },
  {
    id = "rxp.nameplatedistance",
    adapter = "RestedXP",
    key = "MaxNameplateDistance",
    label = "RestedXP: Maximize Nameplate Distance",
    when = { "RXPGuides", "Plater" },
    reason = "It sets nameplate range to 41 at every loading screen, overriding Plater's nameplate distance.",
    needsReload = true,
  },
  {
    id = "leatrix.combatplates",
    adapter = "LeatrixPlus",
    key = "CombatPlates",
    label = "Leatrix Plus: Combat plates",
    when = { "Leatrix_Plus", "Plater" },
    reason = "Plater owns enemy nameplate visibility; Leatrix toggles it at each combat transition.",
    needsReload = true,
  },
  {
    id = "plater.resources",
    adapter = "Plater",
    key = "Resources",
    label = "Plater: Resource bars",
    when = { "Plater", "ClassUIEnhanced" },
    reason = "ClassUIEnhanced owns the player's class resource display.",
  },
  {
    id = "plater.personalbar",
    adapter = "Plater",
    key = "PersonalBar",
    label = "Plater: Personal health and mana bars",
    when = { "Plater", "ClassUIEnhanced" },
    reason = "ClassUIEnhanced owns player health and power tracking; Blizzard unit frames remain available.",
  },
}
