-- QuestForever: where to pick quests up, where to hand them in, and where the
-- things you need are - on the world map and the minimap.
--
-- A module of ForeverUI. ForeverUI loads it (it is load-on-demand) when the
-- quest helper is switched on, hands it its settings, and switches it off
-- again; what it learns while you play it keeps in those settings. The quest
-- data is Data.lua, generated by tools/build_questdata.py.
--
-- What is shown is only what fits the character in front of you: the right
-- faction, race and class, a level you can take it at, not done already (the
-- game says which quests are done), not in your log, and with the quests
-- before it done. Anything the game knows live - your log, which quests are
-- complete, which objectives are finished, what a quest giver is offering -
-- comes from the game, not from the data.
--
-- Where the data doesn't know (a quest new in Forever whose giver nobody has
-- placed yet), it learns: the giver you pick a quest up from and the one you
-- hand it in to are remembered, drawn from then on, and can be shared with
-- /fui qf export so the next data build has them for everyone.

local QF = {}
_G.QuestForever = QF
local D = QuestForeverData or { Q = {}, N = {}, O = {}, I = {} }
QF.data = D

-- Settings: ForeverUI hands over a function that returns its module settings.
local DEFAULTS = {
  showAvailable = true,    -- "!" where you can pick a quest up
  showTurnIns = true,      -- "?" where you hand a finished quest in
  showUnfinished = false,  -- a grey "?" for quests in your log not finished yet
  showObjectives = true,   -- dots where the mobs, items and objects are
  showItemStarts = true,   -- where the items that start quests drop
  showPaths = true,        -- the routes of patrolling and escort NPCs
  tooltips = true,         -- quest lines on mobs' and objects' own tooltips
  onWorldMap = true,
  onMinimap = true,
  hideTrivial = true,      -- quests far below your level
  showRepeatable = false,
  showProfession = false,
  learn = true,            -- remember givers and hand-ins the data lacks
  levelsAhead = 0,         -- also show quests this many levels too high
  iconSize = 16,
}
QF.DEFAULTS = DEFAULTS
local getSettings = function() return DEFAULTS end

local function S(key)
  local s = getSettings() or DEFAULTS
  local v = s[key]
  if v == nil then return DEFAULTS[key] end
  return v
end
QF.Setting = S

local function Secret(v)
  return issecretvalue ~= nil and issecretvalue(v)
end

-- Flag bits written by the generator.
local REPEATABLE, ESCORT, PROFESSION, UNCHAINED = 1, 2, 64, 128
local function Has(flags, bit) return math.floor((flags or 0) / bit) % 2 == 1 end
QF.Has = Has

---------------------------------------------------------------------------
-- Reading the compact data
---------------------------------------------------------------------------

-- "1429:489,364 495,361|1411:520,440" -> { {map, x, y}, ... } with x, y 0-1.
local parsed = {}
function QF.Points(str)
  if not str then return {} end
  local hit = parsed[str]
  if hit then return hit end
  local list = {}
  for chunk in str:gmatch("[^|]+") do
    local map, rest = chunk:match("^(%d+):(.*)$")
    map = tonumber(map)
    if map then
      for x, y in rest:gmatch("(%d+),(%d+)") do
        list[#list + 1] = { map, tonumber(x) / 1000, tonumber(y) / 1000 }
      end
    end
  end
  parsed[str] = list
  return list
end

-- "a||b" -> { "a", "", "b" } (empty labels kept, so they line up with pins).
local function SplitLabels(str)
  local out = {}
  if not str then return out end
  local start = 1
  while true do
    local bar = str:find("|", start, true)
    if not bar then out[#out + 1] = str:sub(start) break end
    out[#out + 1] = str:sub(start, bar - 1)
    start = bar + 1
  end
  return out
end

-- "s1429:489,364 e1411:500,500" -> starts, ends, objectives; each point
-- carries the guide's label for it (who stands there) when there is one.
local function RolePins(str, plabels)
  local s, e, o = {}, {}, {}
  if str then
    local labels = SplitLabels(plabels)
    local i = 0
    for role, map, x, y in str:gmatch("([seo])(%d+):(%d+),(%d+)") do
      i = i + 1
      local label = labels[i]
      if label == "" then label = nil end
      local point = { tonumber(map), tonumber(x) / 1000, tonumber(y) / 1000, label }
      local list = role == "s" and s or role == "e" and e or o
      list[#list + 1] = point
    end
  end
  return s, e, o
end

local function IdList(str)
  local set = {}
  if str then
    for id in str:gmatch("%d+") do set[#set + 1] = tonumber(id) end
  end
  return set
end
QF.IdList = IdList

-- The quest record, unpacked on first use.
local FIELDS = { "name", "level", "reqLevel", "side", "races", "classes", "flags",
  "starts", "ends", "preAll", "preAny", "excl", "obj", "pins", "xp", "rep", "note", "plabels" }
local quests = {}
function QF.Quest(id)
  local q = quests[id]
  if q then return q end
  local raw = D.Q[id]
  if not raw then return nil end
  q = { id = id }
  for i, name in ipairs(FIELDS) do q[name] = raw[i] end
  quests[id] = q
  return q
end

-- A name, or nil when the data doesn't have one ("?" is the generator's
-- placeholder for an NPC it knows only by ID).
function QF.Name(kind, id)
  local rec = (kind == "n" and D.N[id]) or (kind == "o" and D.O[id]) or (kind == "i" and D.I[id])
  local name = rec and rec[1]
  if name == "?" then return nil end
  return name
end

-- Where an NPC or object stands (all its spawn points).
function QF.Spawns(kind, id)
  local rec = (kind == "n" and D.N[id]) or (kind == "o" and D.O[id])
  return rec and QF.Points(rec[2]) or {}
end

-- The route a patrolling NPC walks (escorts, wandering elites).
function QF.Patrol(id)
  local rec = D.N[id]
  return rec and QF.Points(rec[3]) or {}
end

---------------------------------------------------------------------------
-- Learning what the data doesn't know
---------------------------------------------------------------------------

-- learned["S92460"] = { map, x, y, ref, who, name, level }: where a quest
-- was really picked up ("S") or handed in ("E"). Kept in the settings
-- ForeverUI saves.
local function Learned()
  local s = getSettings()
  if not s or s == DEFAULTS then return {} end
  s.learned = s.learned or {}
  return s.learned
end
QF.Learned = Learned

-- A table of its own in the saved settings (notes, routes - Curation.lua),
-- made on first use. Before the settings exist there is nowhere to keep it:
-- a scratch table, so nothing is written to the defaults.
function QF.Store(key)
  local s = getSettings()
  if not s or s == DEFAULTS then return {} end
  s[key] = s[key] or {}
  return s[key]
end

local startCache, endCache = {}, {}
local startsByMap, itemStartsByMap

local function Forget(id)
  startCache[id], endCache[id] = nil, nil
  startsByMap = nil
end

-- Start over from the data (a data table swapped in, or records added).
function QF.Rebuild()
  for k in pairs(startCache) do startCache[k] = nil end
  for k in pairs(endCache) do endCache[k] = nil end
  startsByMap, itemStartsByMap = nil, nil
end

-- A quest the data never heard of gets a record of its own, from the game.
local function Adopt(id, name, level)
  if D.Q[id] or not name then return end
  D.Q[id] = { name, level or 0, 1, 0 }
  quests[id] = nil
end

---------------------------------------------------------------------------
-- Places
---------------------------------------------------------------------------

-- The places a quest is picked up: the guide's pins when it has them, and
-- wherever its giver (an NPC or object) stands, and wherever you picked it
-- up yourself. A quest started by an item is placed where the item drops
-- (see ItemStartPlaces).
local function Places(q, refs, pins, cache, learnedKey)
  local hit = cache[q.id]
  if hit then return hit end
  local list, seen = {}, {}
  local function add(p, who)
    local key = p[1] .. ":" .. math.floor(p[2] * 200) .. "," .. math.floor(p[3] * 200)
    local had = seen[key]
    if not had then
      seen[key] = list
      list[#list + 1] = { p[1], p[2], p[3], who }
      seen[key] = list[#list]
    elseif not had[4] then
      had[4] = who   -- the guide's pin and the giver's spawn: keep the name
    end
  end
  for _, p in ipairs(pins) do add(p, p[4]) end
  if refs then
    for kind, id in refs:gmatch("([no])(%d+)") do
      id = tonumber(id)
      local who = QF.Name(kind, id)
      for _, p in ipairs(QF.Spawns(kind, id)) do add(p, who) end
    end
  end
  local mine = Learned()[learnedKey .. q.id]
  if mine then add(mine, mine[5]) end
  cache[q.id] = list
  return list
end

function QF.StartPlaces(q)
  local s = RolePins(q.pins, q.plabels)
  return Places(q, q.starts, s, startCache, "S")
end

function QF.EndPlaces(q)
  local _, e = RolePins(q.pins, q.plabels)
  return Places(q, q.ends, e, endCache, "E")
end

-- Where whatever drops or holds an item stands, with who that is.
local function ItemSources(itemID, limit)
  local list = {}
  local item = D.I[itemID]
  if not item then return list end
  for _, npc in ipairs(IdList(item[2])) do
    local who = QF.Name("n", npc)
    for _, p in ipairs(QF.Spawns("n", npc)) do
      list[#list + 1] = { p[1], p[2], p[3], who }
      if #list >= limit then return list end
    end
  end
  for _, obj in ipairs(IdList(item[3])) do
    local who = QF.Name("o", obj)
    for _, p in ipairs(QF.Spawns("o", obj)) do
      list[#list + 1] = { p[1], p[2], p[3], who }
      if #list >= limit then return list end
    end
  end
  return list
end

-- Quests that start from an item: where that item drops.
function QF.ItemStartPlaces(q)
  local list = {}
  if not q.starts then return list end
  for id in q.starts:gmatch("i(%d+)") do
    local item = D.I[tonumber(id)]
    for _, p in ipairs(ItemSources(tonumber(id), 40)) do
      list[#list + 1] = { p[1], p[2], p[3], p[4], item and item[1] }
    end
  end
  return list
end

---------------------------------------------------------------------------
-- The character
---------------------------------------------------------------------------

local me = {}
function QF.ReadPlayer()
  me.faction = UnitFactionGroup and UnitFactionGroup("player") or nil
  -- Not `UnitRace and UnitRace(...)`: an `and` keeps only the first return,
  -- the localised name, and the token is the second.
  if UnitRace then
    local _, race = UnitRace("player")
    me.race = race
  end
  if UnitClass then
    local _, class = UnitClass("player")
    me.class = class
  end
  me.level = UnitLevel and UnitLevel("player") or 1
  local ok, range = pcall(function() return UnitQuestTrivialLevelRange and UnitQuestTrivialLevelRange("player") end)
  me.trivial = (ok and type(range) == "number") and range or 8
  return me
end
QF.me = me

-- Quests done, and quests in the log. Done is asked of the game and kept:
-- a quest doesn't become un-done.
local done = {}
function QF.IsDone(id)
  if done[id] then return true end
  local fn = C_QuestLog and C_QuestLog.IsQuestFlaggedCompleted or IsQuestFlaggedCompleted
  if not fn then return false end
  local ok, yes = pcall(fn, id)
  if ok and yes == true then
    done[id] = true
    return true
  end
  return false
end

-- The game's own objective lines for a quest: { {text, finished}, ... }
local function Objectives(questID)
  local list = {}
  local fn = C_QuestLog and C_QuestLog.GetQuestObjectives
  if not fn then return list end
  local ok, objectives = pcall(fn, questID)
  if not ok or type(objectives) ~= "table" then return list end
  for _, o in ipairs(objectives) do
    local text = (type(o.text) == "string" and not Secret(o.text)) and o.text or ""
    local finished = o.finished
    if Secret(finished) then finished = false end
    list[#list + 1] = { text = text, finished = finished == true }
  end
  return list
end

local inLog = {}
function QF.ReadLog()
  for k in pairs(inLog) do inLog[k] = nil end
  local log = C_QuestLog
  if log and log.GetNumQuestLogEntries and log.GetInfo then
    local n = log.GetNumQuestLogEntries() or 0
    for i = 1, n do
      local ok, info = pcall(log.GetInfo, i)
      if ok and type(info) == "table" and not info.isHeader and info.questID then
        local okc, complete = pcall(log.IsComplete, info.questID)
        inLog[info.questID] = { complete = okc and complete == true, objectives = Objectives(info.questID) }
        Adopt(info.questID, info.title, info.level)
      end
    end
  elseif GetNumQuestLogEntries and GetQuestLogTitle then
    for i = 1, GetNumQuestLogEntries() do
      local title, level, _, isHeader, _, isComplete, _, questID = GetQuestLogTitle(i)
      if not isHeader and questID then
        inLog[questID] = { complete = isComplete == 1 or isComplete == true, objectives = Objectives(questID) }
        Adopt(questID, title, level)
      end
    end
  end
  return inLog
end
QF.inLog = inLog

local function Contains(list, value)
  if not list or not value then return false end
  for item in list:gmatch("[^,]+") do
    if item == value then return true end
  end
  return false
end

-- The reputation a quest asks for ("faction:value"): true when you have it,
-- or when the game won't say.
local function HasRep(rep)
  if not rep or not GetFactionInfoByID then return true end
  local faction, value = rep:match("^(%d+):(%-?%d+)$")
  if not faction then return true end
  local ok, name, _, _, _, _, barValue = pcall(GetFactionInfoByID, tonumber(faction))
  if not ok or not name or type(barValue) ~= "number" or Secret(barValue) then return true end
  return barValue >= tonumber(value)
end
QF.HasRep = HasRep

-- Givers you have talked to that didn't offer a quest the data says they
-- would: hidden until something changes (a quest handed in, a level).
local notOffered = {}
QF.notOffered = notOffered

-- Which professions this character has, and how far (Skills.lua says which
-- one a quest needs). Profession skill lines by ID where the game can say
-- (GetProfessions / GetProfessionInfo), else the skill list by English name.
-- Only a source that found a profession counts: if neither finds one (no
-- professions, or a client whose skill names aren't English), every
-- profession quest stays shown, as before.
local SKILL_NAMES = { [129] = "first aid", [164] = "blacksmithing", [165] = "leatherworking",
  [171] = "alchemy", [182] = "herbalism", [185] = "cooking", [186] = "mining", [197] = "tailoring",
  [202] = "engineering", [333] = "enchanting", [356] = "fishing", [393] = "skinning" }
local skillCache, skillAt
function QF.SkillRanks()
  local now = GetTime and GetTime() or 0
  if skillAt and now - skillAt < 30 then return skillCache end
  local ranks, read = {}, false
  if GetProfessions and GetProfessionInfo then
    local ok, a, b, c, d, e = pcall(GetProfessions)
    if ok then
      for _, index in ipairs({ a or false, b or false, c or false, d or false, e or false }) do
        if index then
          local okI, name, _, rank, _, _, _, line = pcall(GetProfessionInfo, index)
          if okI and name and tonumber(line) then
            ranks[tonumber(line)] = tonumber(rank) or 0
            read = true
          end
        end
      end
    end
  end
  if not read and GetNumSkillLines and GetSkillLineInfo then
    local byName = {}
    for id, name in pairs(SKILL_NAMES) do byName[name] = id end
    local okN, n = pcall(GetNumSkillLines)
    for i = 1, (okN and tonumber(n) or 0) do
      local okS, name, header, _, rank = pcall(GetSkillLineInfo, i)
      if okS and type(name) == "string" and not header then
        local id = byName[name:lower()]
        if id then ranks[id] = tonumber(rank) or 0; read = true end
      end
    end
  end
  skillCache, skillAt = read and ranks or nil, now
  return skillCache
end

function QF.ForgetSkills() skillAt = nil end

function QF.HasSkillFor(questID)
  local need = D.SK and D.SK[questID]
  if type(need) ~= "string" then return true end
  local skill, rank = need:match("^(%d+):(%d+)$")
  if not skill then return true end
  local ranks = QF.SkillRanks()
  if not ranks then return true end
  return (ranks[tonumber(skill)] or -1) >= tonumber(rank)
end

-- Can this character pick this quest up now? Returns true, or false and why.
function QF.IsAvailable(q)
  if not q then return false, "unknown" end
  if q.side == 1 and me.faction ~= "Alliance" then return false, "faction" end
  if q.side == 2 and me.faction ~= "Horde" then return false, "faction" end
  if q.races and not Contains(q.races, me.race) then return false, "race" end
  if q.classes and not Contains(q.classes, me.class) then return false, "class" end
  local flags = q.flags or 0
  if Has(flags, REPEATABLE) and not S("showRepeatable") then return false, "repeatable" end
  if Has(flags, PROFESSION) then
    if not S("showProfession") then return false, "profession" end
    -- Shown only to someone who has that profession, far enough along.
    if not QF.HasSkillFor(q.id) then return false, "profession" end
  end
  local ahead = S("levelsAhead") or 0
  if (q.reqLevel or 1) > (me.level or 1) + ahead then return false, "level" end
  -- A Forever quest nobody knows the chain of: its own level stands in for
  -- the quests before it, so a starting island doesn't light up all at once.
  if Has(flags, UNCHAINED) and (q.level or 0) > (me.level or 1) + ahead then return false, "level" end
  if S("hideTrivial") and (q.level or 0) > 0 and (q.level + (me.trivial or 8)) < (me.level or 1) then
    return false, "trivial"
  end
  if inLog[q.id] then return false, "in log" end
  if QF.IsDone(q.id) then return false, "done" end
  for _, pre in ipairs(IdList(q.preAll)) do
    if not QF.IsDone(pre) then return false, "needs an earlier quest" end
  end
  if q.preAny then
    local any = false
    for _, pre in ipairs(IdList(q.preAny)) do
      if QF.IsDone(pre) then any = true break end
    end
    if not any then return false, "needs an earlier quest" end
  end
  for _, other in ipairs(IdList(q.excl)) do
    if QF.IsDone(other) or inLog[other] then return false, "took another" end
  end
  if not HasRep(q.rep) then return false, "reputation" end
  if notOffered[q.id] then return false, "not offered" end
  return true
end

-- Too high for you yet (shown grey when "levels ahead" lets it through).
function QF.IsHigh(q)
  local level = (q.reqLevel or 1)
  if Has(q.flags, UNCHAINED) then level = math.max(level, q.level or 0) end
  return level > (me.level or 1)
end

-- The game's objective line that is about this NPC, item or object (its
-- text names it: "Kobold Vermin slain: 3/10", "Candle: 2/8").
local function ObjectiveLine(state, name)
  if not state or not name then return nil end
  for _, o in ipairs(state.objectives or {}) do
    if o.text ~= "" and o.text:find(name, 1, true) then return o end
  end
  return nil
end
QF.ObjectiveLine = ObjectiveLine

-- Where the work is: the guide's objective pins, the NPCs to kill or talk to,
-- the objects to use, and whatever drops or holds the items to collect.
-- Anything the game says is finished is left out. Each place carries the
-- game's progress line when there is one.
local MAX_OBJECTIVE_POINTS = 80
function QF.ObjectivePlaces(q, state)
  local list = {}
  local _, _, pins = RolePins(q.pins, q.plabels)
  for _, p in ipairs(pins) do list[#list + 1] = { p[1], p[2], p[3], p[4] or q.note } end
  if q.obj then
    for code, id in q.obj:gmatch("([kcut])(%d+)") do
      id = tonumber(id)
      local name = (code == "k" or code == "t") and QF.Name("n", id)
        or code == "u" and QF.Name("o", id) or QF.Name("i", id)
      local line = ObjectiveLine(state, name)
      if not (line and line.finished) then
        local progress = line and line.text or nil
        local function add(p, who)
          list[#list + 1] = { p[1], p[2], p[3], who, progress }
        end
        if code == "k" or code == "t" then
          for _, p in ipairs(QF.Spawns("n", id)) do add(p, name) end
        elseif code == "u" then
          for _, p in ipairs(QF.Spawns("o", id)) do add(p, name) end
        else
          for _, p in ipairs(ItemSources(id, MAX_OBJECTIVE_POINTS)) do
            add(p, (p[4] or "?") .. " (" .. (name or "?") .. ")")
          end
        end
      end
      if #list >= MAX_OBJECTIVE_POINTS then break end
    end
  end
  return list
end

-- The routes worth seeing for a quest in your log: its escort's, and those
-- of the NPCs it sends you after.
function QF.PathPlaces(q)
  local list, ids = {}, {}
  if Has(q.flags, ESCORT) and q.starts then
    for id in q.starts:gmatch("n(%d+)") do ids[#ids + 1] = tonumber(id) end
  end
  if q.obj then
    for id in q.obj:gmatch("[kt](%d+)") do ids[#ids + 1] = tonumber(id) end
  end
  for _, id in ipairs(ids) do
    local who = QF.Name("n", id)
    for _, p in ipairs(QF.Patrol(id)) do list[#list + 1] = { p[1], p[2], p[3], who } end
  end
  return list
end

---------------------------------------------------------------------------
-- What to do
---------------------------------------------------------------------------

-- Up to two names, "A or B", "A, B or 2 others".
local function NameList(names)
  if #names == 0 then return nil end
  if #names == 1 then return names[1] end
  if #names == 2 then return names[1] .. " or " .. names[2] end
  return ("%s, %s or %d others"):format(names[1], names[2], #names - 2)
end

local function SourceNames(itemID)
  local item = D.I[itemID]
  local names, seen = {}, {}
  if item then
    for _, npc in ipairs(IdList(item[2])) do
      local n = QF.Name("n", npc)
      if n and not seen[n] then seen[n] = true; names[#names + 1] = n end
    end
    for _, obj in ipairs(IdList(item[3])) do
      local n = QF.Name("o", obj)
      if n and not seen[n] then seen[n] = true; names[#names + 1] = n end
    end
  end
  return names
end

-- The steps of a quest, in plain words: { text, done, progress, names } -
-- names are the NPCs and objects that step is about (for tooltips). Built
-- from the data's objectives and the game's own objective lines; a game line
-- the data has nothing for is kept as it is, so nothing is left out.
function QF.HowTo(q, state)
  local steps, used = {}, {}
  local lines = state and state.objectives or {}
  -- Who the guide says stands at the objective pins, when the data has no
  -- drop list for an item (a new NPC it has no record of).
  local guide
  local function guideNames()
    if guide then return guide end
    guide = {}
    local seen = {}
    local _, _, pins = RolePins(q.pins, q.plabels)
    for _, p in ipairs(pins) do
      if p[4] and not seen[p[4]] and p[4] ~= q.note then seen[p[4]] = true; guide[#guide + 1] = p[4] end
    end
    return guide
  end
  local function line(name)
    if not name then return nil end
    for i, o in ipairs(lines) do
      if o.text ~= "" and o.text:find(name, 1, true) then used[i] = true; return o end
    end
  end
  if q.obj then
    for code, id in q.obj:gmatch("([kcut])(%d+)") do
      id = tonumber(id)
      local step
      -- A target the data knows only by number (often a hidden "credit"
      -- NPC) is left to the game's own objective line below.
      if code == "k" or code == "t" then
        local npc = QF.Name("n", id)
        if npc then
          step = { text = (code == "k" and "Kill " or "Talk to ") .. npc, names = { npc }, key = npc }
        end
      elseif code == "u" then
        local obj = QF.Name("o", id)
        if obj then step = { text = "Use " .. obj, names = { obj }, key = obj } end
      else
        local item = QF.Name("i", id)
        if item then
          local sources = SourceNames(id)
          if #sources == 0 then sources = guideNames() end
          local from = NameList(sources)
          step = { text = from and ("Loot %s from %s"):format(item, from) or ("Collect " .. item),
            names = sources, key = item, item = item }
        end
      end
      if step then
        local o = line(step.key)
        if o then step.progress, step.done = o.text, o.finished end
        steps[#steps + 1] = step
      end
    end
  end
  if q.note then
    steps[#steps + 1] = { text = "Go to: " .. q.note, names = {} }
  end
  for i, o in ipairs(lines) do
    if not used[i] and o.text ~= "" then
      steps[#steps + 1] = { text = o.text, progress = o.text, done = o.finished, names = {} }
    end
  end
  return steps
end

-- The spot to head for next: the nearest unfinished objective on the map
-- you are on (or the hand-in, once the quest is complete); any map when
-- there is nothing on yours.
local function Here()
  if not (C_Map and C_Map.GetBestMapForUnit and C_Map.GetPlayerMapPosition) then return nil end
  local okMap, map = pcall(C_Map.GetBestMapForUnit, "player")
  if not okMap or not map or Secret(map) then return nil end
  local okPos, pos = pcall(C_Map.GetPlayerMapPosition, map, "player")
  if not okPos or not pos then return map end
  local x, y = pos:GetXY()
  if not x or Secret(x) or Secret(y) then return map end
  return map, x, y
end
QF.Here = Here

function QF.NextStep(questID)
  local q = QF.Quest(questID)
  if not q then return nil end
  local state = inLog[questID]
  local places = (state and state.complete) and QF.EndPlaces(q) or QF.ObjectivePlaces(q, state)
  if #places == 0 and state and not state.complete then places = QF.EndPlaces(q) end
  if #places == 0 then return nil end
  local map, px, py = Here()
  local best, bestD
  for _, p in ipairs(places) do
    local d
    if p[1] == map and px then
      d = (p[2] - px) ^ 2 + (p[3] - py) ^ 2
    elseif p[1] == map then
      d = 1
    else
      d = 10
    end
    if not bestD or d < bestD then best, bestD = p, d end
  end
  return best[1], best[2], best[3], best[4], state and state.complete
end

-- The nearest spot for one step of a quest (a step from QF.HowTo): where
-- the NPCs, objects or droppers it names stand. nil when the data has no
-- place for it.
function QF.StepTarget(questID, step)
  local q = QF.Quest(questID)
  if not (q and step) then return nil end
  local names = {}
  for _, n in ipairs(step.names or {}) do names[#names + 1] = n end
  local places = {}
  for _, p in ipairs(QF.ObjectivePlaces(q, inLog[questID])) do
    local who = p[4] or ""
    for _, n in ipairs(names) do
      if who:find(n, 1, true) then places[#places + 1] = p break end
    end
    if #names == 0 and step.text and step.text:find("^Go to") and who ~= "" and step.text:find(who, 1, true) then
      places[#places + 1] = p
    end
  end
  if #places == 0 then return nil end
  local map, px, py = Here()
  local best, bestD
  for _, p in ipairs(places) do
    local d = (p[1] == map and px) and ((p[2] - px) ^ 2 + (p[3] - py) ^ 2) or (p[1] == map and 1 or 10)
    if not bestD or d < bestD then best, bestD = p, d end
  end
  return best[1], best[2], best[3], best[4]
end

-- Who you hand a quest in to, and on which map: the first known place.
function QF.HandIn(questID)
  local q = QF.Quest(questID)
  if not q then return nil end
  local p = QF.EndPlaces(q)[1]
  if not p then return nil end
  return p[4], p[1], p[2], p[3]
end

-- Point the waypoint arrow at that spot. Returns who/what is there.
function QF.PointTo(questID)
  local map, x, y, who, complete = QF.NextStep(questID)
  if not map then return nil end
  QF.SetWaypoint(map, x, y)
  return who or (complete and "the hand-in") or "the next objective"
end

---------------------------------------------------------------------------
-- What goes on a map
---------------------------------------------------------------------------

-- Every quest's pick-up places, by map, built once.
-- A quest started by an item is started by picking the item up, not by
-- anyone standing somewhere: its "!" is the drop pin (ItemStartIndex, at
-- whoever drops it). The data sometimes carries a start point for such a
-- quest too, and it was drawn as a giver where nobody gives it
-- (goldfish117 on CurseForge, 30 Sept 2026: "The Moss-Twined Heart shows
-- in the pools of Darnassus but is given by a rare in NW Teldrassil").
local function StartsOnlyByItem(raw)
  local starts = raw and raw[8]
  if type(starts) ~= "string" or starts == "" then return false end
  for ref in starts:gmatch("%S+") do
    if ref:sub(1, 1) ~= "i" then return false end
  end
  return true
end
QF.StartsOnlyByItem = StartsOnlyByItem

local function StartIndex()
  if startsByMap then return startsByMap end
  startsByMap = {}
  for id, raw in pairs(D.Q) do
    if not StartsOnlyByItem(raw) then
      local q = QF.Quest(id)
      for _, p in ipairs(QF.StartPlaces(q)) do
        local list = startsByMap[p[1]]
        if not list then list = {}; startsByMap[p[1]] = list end
        list[#list + 1] = { id = id, x = p[2], y = p[3], who = p[4] }
      end
    end
  end
  return startsByMap
end
QF.StartIndex = StartIndex

local function ItemStartIndex()
  if itemStartsByMap then return itemStartsByMap end
  itemStartsByMap = {}
  for id, raw in pairs(D.Q) do
    if raw[8] and raw[8]:find("i", 1, true) then
      for _, p in ipairs(QF.ItemStartPlaces(QF.Quest(id))) do
        local list = itemStartsByMap[p[1]]
        if not list then list = {}; itemStartsByMap[p[1]] = list end
        list[#list + 1] = { id = id, x = p[2], y = p[3], who = p[4], item = p[5] }
      end
    end
  end
  return itemStartsByMap
end

-- Pins that share a spot become one pin: a quest hub is one "!" listing its
-- quests, not a pile of them. Close enough = the same giver.
local HUB = 0.006
local function Gather(pins, into, spacing)
  local cells = {}
  for _, pin in ipairs(pins) do
    local key = pin.group .. ":" .. math.floor(pin.x / spacing + 0.5) .. "," .. math.floor(pin.y / spacing + 0.5)
    local hub = cells[key]
    if not hub then
      hub = { kind = pin.kind, x = pin.x, y = pin.y, who = pin.who, quests = {}, whos = {}, n = 0 }
      cells[key] = hub
      into[#into + 1] = hub
    end
    hub.n = hub.n + 1
    -- The spot drifts to the middle of what it gathers.
    hub.x = hub.x + (pin.x - hub.x) / hub.n
    hub.y = hub.y + (pin.y - hub.y) / hub.n
    if pin.rank and pin.rank < (hub.rank or 99) then hub.kind, hub.rank = pin.kind, pin.rank end
    if pin.who and not hub.whos[pin.who] then hub.whos[pin.who] = true end
    local seen = false
    for _, e in ipairs(hub.quests) do if e.id == pin.entry.id then seen = true break end end
    if not seen then hub.quests[#hub.quests + 1] = pin.entry end
  end
  for _, hub in ipairs(into) do
    if hub.quests[1] then
      hub.quest, hub.name, hub.level = hub.quests[1].id, hub.quests[1].name, hub.quests[1].level
      table.sort(hub.quests, function(a, b) return (a.level or 0) < (b.level or 0) end)
    end
  end
  return into
end

local RANK = { turnin = 1, available = 2, unfinished = 3, high = 4, itemstart = 5, objective = 6, path = 7 }

local function Entry(q, extra)
  local e = { id = q.id, name = q.name, level = q.level, xp = q.xp }
  if extra then for k, v in pairs(extra) do e[k] = v end end
  return e
end

-- Pins for one map: { kind = "available"|"high"|"turnin"|"unfinished"|
-- "itemstart"|"objective"|"path", x, y, who, quests = { {id, name, level,
-- xp, progress}, ... } } - hubs gathered into one pin each.
function QF.PinsFor(mapID)
  local out = {}
  if not mapID then return out end
  local givers, spots = {}, {}
  local function giver(kind, q, x, y, who, extra)
    givers[#givers + 1] = { group = "g", kind = kind, rank = RANK[kind], x = x, y = y, who = who,
      entry = Entry(q, extra) }
  end
  if S("showAvailable") then
    for _, e in ipairs(StartIndex()[mapID] or {}) do
      local q = QF.Quest(e.id)
      if QF.IsAvailable(q) then giver(QF.IsHigh(q) and "high" or "available", q, e.x, e.y, e.who) end
    end
  end
  if S("showItemStarts") then
    for _, e in ipairs(ItemStartIndex()[mapID] or {}) do
      local q = QF.Quest(e.id)
      if QF.IsAvailable(q) then
        spots[#spots + 1] = { group = "i" .. e.id, kind = "itemstart", x = e.x, y = e.y, who = e.who,
          entry = Entry(q, { item = e.item }) }
      end
    end
  end
  for id, state in pairs(inLog) do
    local q = QF.Quest(id)
    if q then
      if (state.complete and S("showTurnIns")) or (not state.complete and S("showUnfinished")) then
        for _, p in ipairs(QF.EndPlaces(q)) do
          if p[1] == mapID then giver(state.complete and "turnin" or "unfinished", q, p[2], p[3], p[4]) end
        end
      end
      if not state.complete and S("showObjectives") then
        for _, p in ipairs(QF.ObjectivePlaces(q, state)) do
          if p[1] == mapID then
            spots[#spots + 1] = { group = "o" .. id, kind = "objective", x = p[2], y = p[3], who = p[4],
              entry = Entry(q, { progress = p[5] }) }
          end
        end
      end
      -- A route someone walked for this quest (Curation.lua): each point
      -- its own numbered dot, in order, never merged with its neighbours.
      if not state.complete and QF.Route then
        for i, p in ipairs(QF.Route(id)) do
          if p[1] == mapID then
            out[#out + 1] = { kind = "route", x = p[2], y = p[3],
              who = ("Route %d%s"):format(i, (p[4] and p[4] ~= "") and (": " .. p[4]) or ""),
              quests = { Entry(q) } }
          end
        end
      end
      if not state.complete and S("showPaths") then
        for _, p in ipairs(QF.PathPlaces(q)) do
          if p[1] == mapID then
            spots[#spots + 1] = { group = "p" .. id, kind = "path", x = p[2], y = p[3], who = p[4],
              entry = Entry(q) }
          end
        end
      end
    end
  end
  Gather(givers, out, HUB)
  -- Spawn points of one quest close together make one dot (a camp of
  -- kobolds is one place to go, not twenty).
  local objectivePins = Gather(spots, {}, 0.025)
  for _, pin in ipairs(objectivePins) do
    local list = {}
    for who in pairs(pin.whos) do list[#list + 1] = who end
    table.sort(list)
    pin.who = table.concat(list, ", ")
    out[#out + 1] = pin
  end
  return out
end

---------------------------------------------------------------------------
-- Learning from play
---------------------------------------------------------------------------

-- "Creature-0-1-0-0-823-000..." -> "n823"; objects -> "o...".
local function RefOf(guid)
  if type(guid) ~= "string" or Secret(guid) then return "" end
  local kind, id = guid:match("^(%a+)%-%d+%-%d+%-%d+%-%d+%-(%d+)")
  if kind == "Creature" then return "n" .. id end
  if kind == "GameObject" then return "o" .. id end
  return ""
end
QF.RefOf = RefOf

-- Where you stand, with a position (learning needs the spot, not just the map).
local function HereExactly()
  local map, x, y = Here()
  if not x then return nil end
  return map, x, y
end

local function Talker()
  for _, unit in ipairs({ "questnpc", "npc" }) do
    local okG, guid = pcall(UnitGUID, unit)
    if okG and guid and not Secret(guid) then
      local okN, name = pcall(UnitName, unit)
      return RefOf(guid), (okN and not Secret(name)) and name or nil
    end
  end
  return "", nil
end

-- Remember where this quest was picked up ("S") or handed in ("E"), when
-- the data had no place for it.
function QF.Learn(role, questID, questName, level)
  if not S("learn") or not questID or questID == 0 or Secret(questID) then return false end
  Adopt(questID, questName, level)
  local q = QF.Quest(questID)
  if not q then return false end
  local known = role == "S" and QF.StartPlaces(q) or QF.EndPlaces(q)
  if #known > 0 then return false end
  local map, x, y = HereExactly()
  if not map then return false end
  local ref, who = Talker()
  Learned()[role .. questID] = { map, x, y, ref, who, q.name or questName, q.level or level or 0 }
  Forget(questID)
  return true
end

-- The lines /fui qf export shows, one place each, for the data build.
function QF.ExportLearned()
  local lines = {}
  for key, v in pairs(Learned()) do
    local role, id = key:match("^([SE])(%d+)$")
    if role then
      lines[#lines + 1] = table.concat({ role, id, v[1], math.floor(v[2] * 1000 + 0.5),
        math.floor(v[3] * 1000 + 0.5), v[4] or "", (v[5] or ""):gsub(";", ","),
        (v[6] or ""):gsub(";", ","), v[7] or 0 }, ";")
    end
  end
  table.sort(lines)
  return table.concat(lines, "\n"), #lines
end

-- What a giver offers, from its gossip list: quests the data says it gives
-- but it didn't offer are hidden until something changes.
function QF.HeardOffer(ref, offered)
  if ref == "" or not offered then return end
  for id in pairs(D.Q) do
    local q = QF.Quest(id)
    if q.starts and (" " .. q.starts .. " "):find(" " .. ref .. " ", 1, true) then
      if offered[id] then
        notOffered[id] = nil
      elseif QF.IsAvailable(q) then
        notOffered[id] = true
      end
    end
  end
end

local function GossipOffers()
  local g = C_GossipInfo
  if not (g and g.GetAvailableQuests) then return nil end
  local ok, list = pcall(g.GetAvailableQuests)
  if not ok or type(list) ~= "table" then return nil end
  local offered, any = {}, false
  for _, info in ipairs(list) do
    local id = type(info) == "table" and info.questID
    if type(id) == "number" and not Secret(id) then offered[id] = true; any = true end
  end
  -- A list the game wouldn't give ids for tells us nothing.
  if #list > 0 and not any then return nil end
  return offered
end

---------------------------------------------------------------------------
-- Pointing the way
---------------------------------------------------------------------------

-- Click a pin: the game's own map pin goes there, and ForeverUI's waypoint
-- arrow (which follows the map pin) points at it.
function QF.SetWaypoint(mapID, x, y)
  if not (C_Map and C_Map.SetUserWaypoint and UiMapPoint and UiMapPoint.CreateFromCoordinates) then
    return false
  end
  local ok = pcall(function()
    C_Map.SetUserWaypoint(UiMapPoint.CreateFromCoordinates(mapID, x, y))
    if C_SuperTrack and C_SuperTrack.SetSuperTrackedUserWaypoint then
      C_SuperTrack.SetSuperTrackedUserWaypoint(true)
    end
  end)
  return ok
end

---------------------------------------------------------------------------
-- On and off
---------------------------------------------------------------------------

QF.running = false
local listeners = {}
function QF.OnChange(fn) listeners[#listeners + 1] = fn end
local function Changed()
  for _, fn in ipairs(listeners) do pcall(fn) end
end
QF.Changed = Changed

local function QuestShown()
  local id = GetQuestID and GetQuestID()
  if not id or Secret(id) then return nil end
  local title = GetTitleText and GetTitleText()
  if Secret(title) then title = nil end
  return id, title
end

local watcher = CreateFrame("Frame")
local EVENTS = { "QUEST_LOG_UPDATE", "QUEST_ACCEPTED", "QUEST_REMOVED", "QUEST_TURNED_IN",
  "PLAYER_LEVEL_UP", "PLAYER_ENTERING_WORLD", "QUEST_DETAIL", "QUEST_COMPLETE", "GOSSIP_SHOW" }
watcher:SetScript("OnEvent", function(_, event, arg1)
  if not QF.running then return end
  if event == "QUEST_DETAIL" or event == "QUEST_COMPLETE" then
    local id, title = QuestShown()
    if id and QF.Learn(event == "QUEST_DETAIL" and "S" or "E", id, title) then Changed() end
    return
  end
  if event == "GOSSIP_SHOW" then
    local ref = Talker()
    QF.HeardOffer(ref, GossipOffers())
    Changed()
    return
  end
  if event == "QUEST_TURNED_IN" and arg1 then done[arg1] = true end
  if event == "QUEST_TURNED_IN" or event == "PLAYER_LEVEL_UP" then
    for k in pairs(notOffered) do notOffered[k] = nil end
  end
  if event == "PLAYER_LEVEL_UP" then
    QF.ReadPlayer()
    me.level = arg1 or me.level
  end
  QF.ReadLog()
  Changed()
end)
QF.watcher = watcher

function QF.Start(settingsFn)
  if settingsFn then getSettings = settingsFn end
  QF.running = true
  for _, event in ipairs(EVENTS) do pcall(watcher.RegisterEvent, watcher, event) end
  QF.ReadPlayer()
  QF.ReadLog()
  -- What was learned before goes back on the map.
  for key in pairs(Learned()) do
    local id = tonumber(key:match("^[SE](%d+)$"))
    if id then
      local v = Learned()[key]
      Adopt(id, v[6], v[7])
      Forget(id)
    end
  end
  if QF.StartPins then QF.StartPins() end
  Changed()
  return true
end

function QF.Stop()
  QF.running = false
  watcher:UnregisterAllEvents()
  if QF.StopPins then QF.StopPins() end
end

function QF.Refresh()
  if not QF.running then return end
  QF.ReadPlayer()
  QF.ReadLog()
  Changed()
end

function QF.Counts()
  local c = {}
  for k, v in pairs(D.counts or {}) do c[k] = v end
  local n = 0
  for _ in pairs(Learned()) do n = n + 1 end
  c.learned = n
  return c
end
