-- =============================================================================
-- DungeonsForever · English (enUS) data overlay — Data_ExplorePets.lua
-- Generated by _temp/gen_enus_data.py — DO NOT hand-edit.
-- Corrections go into _temp/enus_data*.py, then re-run the generator.
-- Loads on the enUS client only; other locales exit immediately.
-- =============================================================================

local _, ns = ...

if (type(GetLocale) ~= "function") or GetLocale() ~= "enUS" then return end

local _, ns = ...

ns.ExplorePets = {
    [1] = {
        282047, "inv_pet_babycrocodile_toothy", "A", "party",
        1519, false, false, "Canals · Rare-elite drop",
        {
            { t = "Kill the elite patrolling the canal, the Sewer Beast",
              m = { { "Sewer Beast", 1519, false, false } } },
            { t = "It has a chance to drop the Baby Crocolisk; it is very tanky, so bring a group" },
        },
    },
    [2] = {
        275682, "inv_maldraxxusslime", "H", "solo",
        1497, false, false, "Canals · Interactive",
        {
            { t = "Buy a Nutritious Slime Sludge from the vendor Boyle",
              m = { { "Boyle", 1497, 56.2, 64.6 },
                    { "Nutritious Slime Sludge", 1497, 56.2, 64.6 } } },
            { t = "Jump into the canal and find the patrolling Excitable Slime",
              m = { { "Excitable Slime", 1497, false, false } } },
            { t = "Spam /dance at it until it dances back and offers you a quest" },
            { t = "Hand it the sludge to get the Excitable Slime. Afterwards /dance at the pet and it dances too" },
        },
    },
    [3] = {
        268109, "inv_frog2_blue", nil, "easy",
        16593, 51.8, 71.7, "Waterfall-top log · Interactive",
        {
            { t = "Follow the road south across the field and jump onto the log at the top of the waterfall" },
            { t = "Target a Musical Gustjumper and use /sing; the flock vanishes",
              m = { { "Musical Gustjumper", 16593, 51.8, 71.7 } } },
            { t = "Click the frog that appears on the log to get the Musical Gustjumper" },
        },
    },
}

ns.ExplorePetMeta = {
    updated = "2026-10-01",
}
