-- =============================================================================
-- DungeonsForever · English (enUS) data overlay — Data_Dungeons.lua
-- Generated by _temp/gen_enus_data.py — DO NOT hand-edit.
-- Corrections go into _temp/enus_data*.py, then re-run the generator.
-- Loads on the enUS client only; other locales exit immediately.
-- =============================================================================

local _, ns = ...

if (type(GetLocale) ~= "function") or GetLocale() ~= "enUS" then return end

local _, ns = ...

ns.DungeonData = {
    dungeons = {
        { id = "hall_of_thanes",     name = "Hall of Lords",       nameEn = "Hall of Thanes",            levelMin = 13, levelMax = 18, isNew = true,  zone = "Under Ironforge, Dun Morogh",   bossCount = 4,  dropCount = 13,  art = "art-hall-of-thanes",     bosses = {} },
        { id = "ragefire_chasm",     name = "Ragefire Chasm",       nameEn = "Ragefire Chasm",           levelMin = 13, levelMax = 18, isNew = false, zone = "Orgrimmar",             bossCount = 4,  dropCount = 12,  art = "art-ragefirechasm",      bosses = {} },
        { id = "ruins_of_lordaeron", name = "Ruins of Lordaeron",     nameEn = "Ruins of Lordaeron",       levelMin = 15, levelMax = 20, isNew = true,  zone = "Ruins of Lordaeron",           bossCount = 7,  dropCount = 20,  art = "art-ruins-of-lordaeron", bosses = {} },
        { id = "wailing_caverns",    name = "Wailing Caverns",       nameEn = "Wailing Caverns",          levelMin = 17, levelMax = 24, isNew = false, zone = "The Barrens",             bossCount = 10, dropCount = 30,  art = "art-wailingcaverns",     bosses = {} },
        { id = "the_deadmines",      name = "The Deadmines",       nameEn = "The Deadmines",            levelMin = 17, levelMax = 26, isNew = false, zone = "Westfall",             bossCount = 11, dropCount = 48,  art = "art-deadmines",          bosses = {} },
        { id = "shadowfang_keep",    name = "Shadowfang Keep",       nameEn = "Shadowfang Keep",          levelMin = 22, levelMax = 30, isNew = false, zone = "Silverpine Forest",             bossCount = 14, dropCount = 44,  art = "art-shadowfangkeep",     bosses = {} },
        { id = "excavation_wetlands",name = "Excavation site: Wetlands",   nameEn = "Excavation Site: Wetlands",levelMin = 24, levelMax = 29, isNew = true,  zone = "Wetlands, above the Verga excavation site", bossCount = 4,  dropCount = 10, art = "art-excavation-site",    bosses = {} },
        { id = "blackfathom_deeps",  name = "Blackfathom Deeps",       nameEn = "Blackfathom Deeps",        levelMin = 24, levelMax = 32, isNew = false, zone = "Ashenvale",                 bossCount = 9,  dropCount = 36,  art = "art-blackfathomdeeps",   bosses = {} },
        { id = "the_stockade",       name = "The Stockade",           nameEn = "The Stockade",             levelMin = 24, levelMax = 32, isNew = false, zone = "Stormwind City",               bossCount = 7,  dropCount = 18,   art = "art-stockade",           bosses = {} },
        { id = "city_of_dalaran",    name = "City of Dalaran",       nameEn = "City of Dalaran",          levelMin = 28, levelMax = 33, isNew = true,  zone = "Alterac Mountains",         bossCount = 9,  dropCount = nil, art = "art-city-of-dalaran",    bosses = {} },
        { id = "gnomeregan",         name = "Gnomeregan",       nameEn = "Gnomeregan",               levelMin = 29, levelMax = 38, isNew = false, zone = "Dun Morogh",               bossCount = 8,  dropCount = 43,  art = "art-gnomeregan",         bosses = {} },
        { id = "razorfen_kraul",     name = "Razorfen Kraul",       nameEn = "Razorfen Kraul",           levelMin = 29, levelMax = 38, isNew = false, zone = "The Barrens",             bossCount = 10,  dropCount = 34,  art = "art-razorfenkraul",      bosses = {} },
        { id = "sm_graveyard",       name = "Scarlet Monastery: Graveyard", nameEn = "Scarlet Monastery Graveyard", levelMin = 30, levelMax = 38, isNew = false, zone = "Tirisfal Glades",   bossCount = 6,  dropCount = 41,  art = "art-scarletmonastery",   bosses = {} },
        { id = "sm_library",         name = "Scarlet Monastery: Library", nameEn = "Scarlet Monastery Library", levelMin = 33, levelMax = 41, isNew = false, zone = "Tirisfal Glades",   bossCount = 4,  dropCount = 36,  art = "art-scarlethalls",       bosses = {} },
        { id = "the_drowned_city",   name = "The Sunken City",       nameEn = "The Drowned City",         levelMin = 35, levelMax = 40, isNew = true,  zone = "Off the coast of Stranglethorn",           bossCount = nil, dropCount = nil, art = "art-the-drowned-city",  bosses = {} },
        { id = "sm_armory",          name = "Scarlet Monastery: Armory", nameEn = "Scarlet Monastery Armory", levelMin = 36, levelMax = 44, isNew = false, zone = "Tirisfal Glades",   bossCount = 2,  dropCount = 33,  art = "art-scarlethalls",       bosses = {} },
        { id = "razorfen_downs",     name = "Razorfen Downs",       nameEn = "Razorfen Downs",           levelMin = 37, levelMax = 46, isNew = false, zone = "The Barrens",             bossCount = 8,  dropCount = 31,  art = "art-razorfendowns",      bosses = {} },
        { id = "sm_cathedral",       name = "Scarlet Monastery: Cathedral", nameEn = "Scarlet Monastery Cathedral", levelMin = 38, levelMax = 46, isNew = false, zone = "Tirisfal Glades",  bossCount = 4,  dropCount = 38,  art = "art-scarletmonastery",   bosses = {} },
        { id = "kroldok_stronghold", name = "Krodedor Keep",   nameEn = "Krol'dok Stronghold",      levelMin = 40, levelMax = 45, isNew = true,  zone = "Riverveil Woods (new zone)",   bossCount = nil, dropCount = nil, art = "art-kroldok-stronghold", bosses = {} },
        { id = "uldaman",            name = "Uldaman",         nameEn = "Uldaman",                  levelMin = 41, levelMax = 51, isNew = false, zone = "Badlands",             bossCount = 15, dropCount = 59,  art = "art-uldaman",            bosses = {} },
        { id = "zul_farrak",         name = "Zul'Farrak",     nameEn = "Zul'Farrak",               levelMin = 44, levelMax = 54, isNew = false, zone = "Tanaris",             bossCount = 14, dropCount = 39,  art = "art-zulfarrak",          bosses = {} },
        { id = "maraudon",           name = "Maraudon",         nameEn = "Maraudon",                 levelMin = 46, levelMax = 55, isNew = false, zone = "Desolace",             bossCount = 15, dropCount = 40,  art = "art-maraudon",           bosses = {} },
        { id = "alcaz_prison",       name = "Prison of Alcaz",     nameEn = "Alcaz Prison",             levelMin = 48, levelMax = 53, isNew = true,  zone = "Alcaz Island, Dustwallow Marsh",   bossCount = nil, dropCount = nil, art = "art-alcaz-prison",      bosses = {} },
        { id = "sunken_temple",      name = "The Temple of Atal'Hakkar",     nameEn = "Sunken Temple",            levelMin = 50, levelMax = 60, isNew = false, zone = "Swamp of Sorrows",             bossCount = 12, dropCount = 104, art = "art-sunkentemple",       bosses = {} },
        { id = "blackrock_depths",   name = "Blackrock Depths",       nameEn = "Blackrock Depths",         levelMin = 52, levelMax = 60, isNew = false, zone = "Blackrock Mountain",               bossCount = 29, dropCount = 180, art = "art-blackrockdepths",    bosses = {} },
        { id = "dire_maul_east",     name = "Dire Maul: East",   nameEn = "Dire Maul East",           levelMin = 54, levelMax = 60, isNew = false, zone = "Feralas",               bossCount = 6,  dropCount = 56,  art = "art-diremaul",           bosses = {} },
        { id = "blackmaw_hold",      name = "Blackthroat Keep",       nameEn = "Blackmaw Hold",            levelMin = 55, levelMax = 60, isNew = true,  zone = "Beyond the gates of Azshara",     bossCount = nil, dropCount = nil, art = "art-blackmaw-hold",     bosses = {} },
        { id = "lower_blackrock_spire", name = "Lower Blackrock Spire",  nameEn = "Lower Blackrock Spire",    levelMin = 55, levelMax = 60, isNew = false, zone = "Blackrock Mountain",               bossCount = 17, dropCount = 93,  art = "art-blackrockspire",     bosses = {} },
        { id = "dire_maul_north",    name = "Dire Maul: North",   nameEn = "Dire Maul North",          levelMin = 56, levelMax = 60, isNew = false, zone = "Feralas",               bossCount = 10, dropCount = 126, art = "art-diremaul",           bosses = {} },
        { id = "dire_maul_west",     name = "Dire Maul: West",   nameEn = "Dire Maul West",           levelMin = 56, levelMax = 60, isNew = false, zone = "Feralas",               bossCount = 9,  dropCount = 69,  art = "art-diremaul",           bosses = {} },
        { id = "scholomance",        name = "Scholomance",       nameEn = "Scholomance",              levelMin = 58, levelMax = 60, isNew = false, zone = "Western Plaguelands",           bossCount = 16, dropCount = 292, art = "art-scholomance",        bosses = {} },
        { id = "shapers_terrace",    name = "The Shaper's Terrace",     nameEn = "Shaper's Terrace",         levelMin = 58, levelMax = 60, isNew = true,  zone = "Un'Goro Crater",         bossCount = nil, dropCount = nil, art = "art-shapers-terrace",    bosses = {} },
        { id = "stratholme_main",    name = "Stratholme: Main Gate", nameEn = "Stratholme Main Gate",     levelMin = 58, levelMax = 60, isNew = false, zone = "Eastern Plaguelands",           bossCount = 13, dropCount = 106, art = "art-stratholme",         bosses = {} },
        { id = "stratholme_service", name = "Stratholme: Service Entrance", nameEn = "Stratholme Service Gate",  levelMin = 58, levelMax = 60, isNew = false, zone = "Eastern Plaguelands",           bossCount = 10, dropCount = 112, art = "art-stratholme",         bosses = {} },
        { id = "upper_blackrock_spire", name = "Upper Blackrock Spire",  nameEn = "Upper Blackrock Spire",    levelMin = 59, levelMax = 60, isNew = false, zone = "Blackrock Mountain",               bossCount = 10, dropCount = 89,  art = "art-blackrockspire",     bosses = {} },
    },
}
