-- =============================================================================
-- DungeonsForever · English (enUS) data overlay — Data_MapPins.lua
-- Generated by _temp/gen_enus_data.py — DO NOT hand-edit.
-- Corrections go into _temp/enus_data*.py, then re-run the generator.
-- Loads on the enUS client only; other locales exit immediately.
-- =============================================================================

local _, ns = ...

if (type(GetLocale) ~= "function") or GetLocale() ~= "enUS" then return end

local _, ns = ...

ns.MapPins = {
    ["hall_of_thanes"] = {
        entrance = { { 50.9, 93.4 } },
        quest = { { 40, 63.8, 96395 }, { 54.6, 16.9, 98423 } },
    },
    ["ragefire_chasm"] = {
        entrance = { { 61, 8.6 } },
    },
    ["ruins_of_lordaeron"] = {
        entrance = { { 61, 21.6 } },
        quest = { { 62.4, 28.5, 95250 } },
    },
    ["shadowfang_keep"] = {
        object = { { 37.3, 53.8, 6895 }, { 47.2, 79.3, 6283, 6 } },
    },
    ["the_deadmines"] = {
        entrance = { { 30.8, 15.7 } },
    },
    ["wailing_caverns"] = {
        entrance = { { 47.1, 60.3 } },
    },
}
