-- GENERATED by tools/make_whatsnew.py from ForeverUI/CHANGELOG.md -- do not edit by hand.
local _, ns = ...

ns.WHATS_NEW = {
  { version = "0.4.65", items = {
    { "Blizzard's party frames are hidden by default.", "ForeverUI's party and raid frames replace them, and players were seeing both sets. To keep Blizzard's, untick /fui frames > \"Hide Blizzard's party frames\" and /reload. One exception: with the controller interface on and Edit Mode's raid-style party frames, Blizzard's stay up, because the controller's targeting cursor picks party members on those frames. The D-pad's party 1-4 targeting needs no frames and works either way." },
  } },
  { version = "0.4.64", items = {
    { "Fixed: the micro bar's Bags button did nothing", "with Blizzard's bag bar hidden (the default) since 0.4.62. The game won't hand a click to a hidden button; Blizzard's backpack button is now kept clickable, off screen." },
    { "Social on the micro bar", "opens the friends list through the game's own /friends instead of a script, which could leave the character sheet throwing errors afterwards. With a player targeted it tells you to press O instead (there /friends would add them as a friend)." },
    { "Party and raid frames in a group:", "class colours, class names, trimmed names, the Roles list and the AGGRO list no longer break on the names and classes the game keeps hidden in groups - in some setups the frames stopped drawing. Raid marks now show on the frames." },
    { "Each grid acts as its own role:", "the tank grid keeps its target, AGGRO wash and threat meter while you play healer, other grids no longer get threat meters while you tank, and each grid's frames always get that grid's own clicks (a player joining mid-fight could get another role's spells). The focus frame follows your role after a switch." },
    { "Cast Bar > \"Lock it where it is\"", "works now." },
    { "Options:", "colour swatches in two-column cards sit in their own column (Chat, Nameplates)." },
    { "Profile exports and backups", "no longer carry diagnostic logs (errors from other addons, cast traces)." },
    { "Fewer game-setting writes:", "nameplate and action bar settings are only written to the game when they actually change." },
    { "", "Smaller fixes: one failed after-combat job no longer drops the others; textures in each role's own look are repaired after a folder rename; the frames' error notice names the command that shows it." },
  } },
  { version = "0.4.63", items = {
    { "With a controller, the quest guide no longer pops up on every quest you pick up.", "It is a mouse window that the controller's B button doesn't close, so it sat over the game at every quest giver. With the controller interface on it now stays closed unless you want it: Quests > \"...also with a controller\". Keyboard and mouse are unchanged, and the guide still opens from the quest list any time." },
  } },
  { version = "0.4.62", items = {
    { "Fixed: an error every time you open the character sheet", "(TextStatusBar.lua:110, \"execution tainted by 'ForeverUI'\"). The micro bar's Bags button and the bag window's x opened and closed Blizzard's bags from ForeverUI's own code. The next Escape then closed the bags and the character sheet in ForeverUI's name, and from then on every C failed. Bags now hands its click to Blizzard's own backpack button, and the x is Blizzard's own close button, so the game opens and closes its bags itself." },
    { "Quest kills left on the nameplate.", "A mob your quests still need shows how many are left beside its plate - \"3/10\" - and the same for a mob that drops a quest item. It updates as you kill and loot and goes away when the objective is done. Needs QuestForever switched on. Nameplates > NPCs > \"Quest kills left beside the plate\". In a group the game can hide mob names, and then no count shows." },
  } },
  { version = "0.4.61", items = {
    { "Fixed: item links in chat showing an item number and not clickable.", "ForeverUI's chat turns :) and friends into emoji - and an item link's own code often ends in \"::|h\", which holds the \":|\" face. The link was rewritten into an emoji and broke. Links, icons and the game's other codes in a chat line are now left exactly as they are; only the words around them get emoji and clickable web links." },
  } },
  { version = "0.4.60", items = {
    { "Sell junk by itself at vendors.", "Loot > \"Sell junk (grey items) by itself at vendors\": open a vendor and your grey items are sold through the game's own sell-all-junk, so nothing that isn't grey is ever touched. It says in chat what it sold and for how much. Off unless you turn it on; kept through the beta's saving bug." },
    { "No more bags full of \"new\" glow after a reload.", "The game takes an item's new-item glow off when its bag window closes, and ForeverUI's bag window never went through that, so everything stayed lit. The glow is now forgotten when the bags close and when you enter the world. Bags > \"Forget the new-item glow when the bags close\" turns that off." },
    { "The Social tile opens your friends list.", "Forever has no Social button of its own for the micro bar to hand the click to, so every click only said \"press O\". The tile now opens it directly, the same way the O key does." },
    { "Fixed on keyboard and mouse: \"ActionBarButton.lua:842: bad argument #1 to 'SetChecked' ... Secret values are only allowed during untainted execution\"", "(druids, paladins and warriors, often when shifting form). The game sets up its controller bar's class-spell button when you log in and switches it back on, after ForeverUI had put the hidden controller buttons to sleep. They're now put back to sleep once you're in the world." },
  } },
  { version = "0.4.59", items = {
    { "Fixed: CompactUnitFrame errors from Edit Mode and the flight master", "(\"CompactUnitFrame.lua:699 ... secret number value, while execution tainted by 'ForeverUI'\", and the \"outOfRange\" one after it). ForeverUI put Blizzard's own player, target and target-of-target frames away by hiding them, and hiding the target-of-target runs a bit of Blizzard's code that reconfigures the target frame - under ForeverUI's name. Edit Mode reads the target frame on the way in and out, so its whole pass ran as ForeverUI, Blizzard's party frames were redrawn as ForeverUI, and they kept that name afterwards (which is the flight master one). Blizzard's protected frames are now faded out and made unclickable instead, which runs none of their code." },
  } },
  { version = "0.4.58", items = {
    { "Fixed: CompactUnitFrame errors in combat", "(\"CompactUnitFrame.lua:699: attempt to compare local 'oldR' (a secret number value, while execution tainted by 'ForeverUI')\" and the \"outOfRange\" one after it, usually the moment a mob targets you). When ForeverUI hid Blizzard's own nameplates, the game ran Blizzard's hide code under ForeverUI's name, and that code signed the plate up for its health and threat updates as ForeverUI - so every threat change in a fight ran Blizzard's code as ForeverUI. Blizzard's plate is now simply made invisible instead, which runs none of its code. The same goes for Blizzard's party and raid frames when you choose to hide them: they no longer listen for anything once put away." },
  } },
}
