--[[
    TrinketData[live] -- equipped-trinket effect database (auto-generated).

    Generated by ItemInfoDB/generate_trinkets.py --channel live from DB2 build 12.1.0.69382.
    Scope: ItemSparse InventoryType 12, ExpansionID 10/11. TOC interface 120100.
    DO NOT EDIT BY HAND -- re-run the generator after refreshing the CSVs.

    Registered into the version-gated registry in Core/TrinketData.lua; the
    dataset whose interface is the highest <= the client interface wins.

    onUse[itemID] = duration  -- buff duration in seconds. Cooldown + detection
      are read live (GetInventoryItemCooldown / GetItemSpell); only the buff
      duration needs a reliable source. Items absent here fall back to parsing.

    proc[itemID]  = { ids = {...}, durs = {...}, stack = spellID? }
      ids[1]  = longest-duration buff = active-window timer (start -> start+dur).
                A proc buff spellID is what SPELL_UPDATE_COOLDOWN arg1 reports.
      durs    = buff durations (seconds), parallel to ids.
      stack   = spellID whose repeated procs are counted as stacks (nil if none).

    stacks[itemID] = spellID  -- a passive with no window to time, only a
      stacking aura (named by the $<id>u max-stack token). The tracker shows the
      icon and binds that aura's stack count engine-side.
--]]

local _
---@type string, private
local addonName, private = ...

-- Skip construction entirely when this dataset cannot win the selection
-- (a release dataset at the same interface already registered). The table
-- below is several hundred entries and would be built only to be discarded.
if not private.TrinketDataWouldWin(120100, "live") then return end

private.RegisterTrinketData(120100, "12.1.0.69382", "live", {
    onUse = {
        [212450] = 3,  -- Swarmlord's Authority (Ravenous Swarm)
        [215170] = 60,  -- Abyssal Trap (Abyssal Trap)
        [215172] = 15,  -- Silken Chain Weaver (Silken Chain Weaver)
        [215174] = 30,  -- Concoction: Kiss of Death (Concoction: Kiss of Death)
        [217041] = 10,  -- Horn of Declaration (Horn of Declaration)
        [218421] = 15,  -- Forged Aspirant's Badge of Ferocity (Gladiator's Badge)
        [218424] = 15,  -- Forged Aspirant's Emblem (Gladiator's Emblem)
        [218713] = 15,  -- Forged Gladiator's Badge of Ferocity (Gladiator's Badge)
        [218715] = 15,  -- Forged Gladiator's Emblem (Gladiator's Emblem)
        [219300] = 15,  -- Skarmorak Shard (Skarmorak Shard)
        [219303] = 10,  -- High Speaker's Accretion (High Speaker's Accretion)
        [219308] = 20,  -- Signet of the Priory (Bolstering Light)
        [219310] = 20,  -- Bursting Lightshard (Bursting Lightshard)
        [219318] = 3,  -- Oppressive Orator's Larynx (Oppressive Oration)
        [219915] = 20,  -- Foul Behemoth's Chelicera (Digestive Venom)
        [219917] = 30,  -- Creeping Coagulum (Creeping Coagulum)
        [219933] = 15,  -- Algari Competitor's Emblem (Gladiator's Emblem)
        [220202] = 20,  -- Spymaster's Web (Spymaster's Web)
        [220305] = 20,  -- Ovi'nax's Mercurial Egg (Suspended Incubation)
        [225649] = 20,  -- Quickwick Candlestick (Quickwick's Quick Trick Wick Walk)
        [225654] = 20,  -- Imperfect Ascendancy Serum (Ascension)
        [225656] = 15,  -- Goldenglow Censer (Golden Glow)
        [226166] = 12,  -- Message-Imprinted Silken Square (Silken Square Pheromones)
        [229491] = 15,  -- Prized Aspirant's Badge of Ferocity (Gladiator's Badge)
        [229494] = 15,  -- Prized Aspirant's Emblem (Gladiator's Emblem)
        [229780] = 15,  -- Prized Gladiator's Badge of Ferocity (Gladiator's Badge)
        [229782] = 15,  -- Prized Gladiator's Emblem (Gladiator's Emblem)
        [230019] = 5,  -- Vexie's Pit Whistle (Pitbot Geardo)
        [230027] = 15,  -- House of Cards (House of Cards)
        [230029] = 20,  -- Chromebustible Bomb Suit (Chromebustible Bomb Suit)
        [230188] = 4,  -- Gallagio Bottle Service (Gallagio Bottle Service)
        [230190] = 15,  -- Torq's Big Red Button (Torq's Big Red Button)
        [230191] = 15,  -- Flarendo's Pilot Light (Flarendo's Pilot Light)
        [230197] = 5,  -- Geargrinder's Spare Keys (Geargrinder's Remote)
        [230352] = 15,  -- Astral Aspirant's Badge of Ferocity (Gladiator's Badge)
        [230355] = 15,  -- Astral Aspirant's Emblem (Gladiator's Emblem)
        [230638] = 15,  -- Astral Gladiator's Badge of Ferocity (Gladiator's Badge)
        [230640] = 15,  -- Astral Gladiator's Emblem (Gladiator's Emblem)
        [232543] = 10,  -- Ringing Ritual Mud (Mudborne)
        [232546] = 2,  -- K.U.-J.0.'s Flame Vents (K.U.-J.O.'s Flame Vents)
        [235984] = 2.5,  -- Garbagemancer's Last Resort (Garbagemancer's Last Resort)
        [240171] = 20,  -- Observer's Soul Fetters (Observer's Soul Fetters)
        [242391] = 20,  -- Soulbinder's Embrace (Soulbinder's Embrace)
        [242393] = 10,  -- Loom'ithar's Living Silk (Loom'ithar's Living Silk)
        [242396] = 20,  -- Unyielding Netherprism (Unyielding Netherprism)
        [242402] = 30,  -- Araz's Ritual Forge (Araz's Ritual Forge)
        [242403] = 4,  -- Perfidious Projector (Perfidious Projector)
        [242494] = 15,  -- Lily of the Eternal Weave (Woven Fate)
        [245753] = 15,  -- Thalassian Competitor's Emblem (Gladiator's Emblem)
        [246825] = 10,  -- Chaotic Nethergate (Chaotic Nethergate)
        [249340] = 2,  -- Wraps of Cosmic Madness (Wraps of Cosmic Madness)
        [249344] = 15,  -- Light Company Guidon (Charge!)
        [249346] = 15,  -- Vaelgor's Final Stare (Nullsight)
        [249808] = 30,  -- Litany of Lightblind Wrath (Beacon of Lightblind Wrath)
        [250144] = 15,  -- Emberwing Feather (Emberwing Heatwave)
        [250215] = 15,  -- Freightrunner's Flask (Freightrunner's Flask)
        [250225] = 20,  -- Void Execution Mandate (Void Execution Mandate)
        [250243] = 10,  -- Manaheart's Binding Flame (Binding Flame)
        [250254] = 12,  -- Seed of Radiant Hope (Seed of Radiant Hope)
        [251786] = 10,  -- Ever-Collapsing Void Fissure (Ever-collapsing Void Fissure)
        [251787] = 20,  -- Sealed Chaos Urn (Sealed Chaos Urn)
        [251789] = 20,  -- Consecrated Chalice (Consecrated Chalice)
        [252411] = 20,  -- Radiant Sunstone (Radiant Blessing)
        [252418] = 15,  -- Solar Core Igniter (Solar Core Igniter)
        [252421] = 15,  -- Rotting Globule (Rotting Globule)
        [255326] = 15,  -- Galactic Aspirant's Badge of Ferocity (Gladiator's Badge)
        [255329] = 15,  -- Galactic Aspirant's Emblem (Gladiator's Emblem)
        [255613] = 15,  -- Galactic Gladiator's Badge of Ferocity (Gladiator's Badge)
        [255615] = 15,  -- Galactic Gladiator's Emblem (Gladiator's Emblem)
        [259896] = 10,  -- Bark of the Guardian Tree (Shield of the Guardian Tree)
        [264694] = 60,  -- Ultradon Cuirass (Ultradon Cuirass)
        [267077] = 15,  -- Novice Combatant's Emblem (Gladiator's Emblem)
        [270160] = 30,  -- First Mate's Shellward (First Mate's Shellward)
        [270162] = 2,  -- Soulcoiler Ritual Vessel (Soulcoiler Ritual Vessel)
        [270168] = 2,  -- Font of Venomous Rage (Font of Venomous Rage)
        [270169] = 30,  -- Hex Lord's Dooming Idol (Hex Lord's Doom)
        [270175] = 20,  -- Voracious Heart of Ula'tek (Voracious Heart of Ula'tek)
        [270555] = 15,  -- Venomous Aspirant's Emblem (Gladiator's Emblem)
        [270559] = 15,  -- Venomous Aspirant's Badge of Ferocity (Gladiator's Badge)
        [270602] = 15,  -- Venomous Gladiator's Badge of Ferocity (Gladiator's Badge)
        [270606] = 15,  -- Venomous Gladiator's Emblem (Gladiator's Emblem)
        [273649] = 20,  -- Stormbound Emblem of Dazar (The King's Unyielding Wind)
        [273796] = 15,  -- Vile Vial of Volatile Venom (Empowering Venom)
        [273797] = 15,  -- Tattered Amani War Banner (Tattered Amani War Banner)
        [274497] = 3.5,  -- Spirit-Rending Poison (Spirit-Rending Poison)
        [274498] = 20,  -- Spirit Ward (Spirit Ward)
        [274891] = 12,  -- Mk XII Gear Drive (Mk XII Gear Drive)
        [280047] = 10,  -- Feathered Bell (Feathered Bell)
        [280091] = 6,  -- Latent Purifier (Latent Purifier)
        [280376] = 12,  -- Shadow Shard Sliver (Shadow Shard Sliver)
        [280377] = 4,  -- Breath of Jan'alai (Breath of Jan'alai)
    },

    proc = {
        [210816] = { ids = {60229}, durs = {15} },  -- Algari Alchemist Stone [Strength]
        [212452] = { ids = {452816, 452565}, durs = {15, 10}, stack = 452565 },  -- Gruesome Syringe [Volatile Serum / Gruesome Intellect]
        [215169] = { ids = {440635}, durs = {30}, stack = 440635 },  -- Everburning Lantern [Lamp Light]
        [215171] = { ids = {438685}, durs = {3} },  -- Fungal Friend Flute [Roughousing]
        [215178] = { ids = {440389}, durs = {10} },  -- Shadow-Binding Ritual Knife [Shadow-Binding Ritual Knife]
        [217894] = { ids = {441428}, durs = {20} },  -- Nerubian Pheromone Secreter [Nerubian Pheromones]
        [218307] = { ids = {442801}, durs = {11} },  -- Wildfire Wick [Wildfire Wick]
        [218423] = { ids = {345230}, durs = {20} },  -- Forged Aspirant's Insignia of Alacrity [Gladiator's Insignia]
        [218425] = { ids = {336139}, durs = {60} },  -- Forged Aspirant's Sigil of Adaptation [Adapted]
        [218714] = { ids = {345230}, durs = {20} },  -- Forged Gladiator's Insignia of Alacrity [Gladiator's Insignia]
        [218717] = { ids = {336139}, durs = {60} },  -- Forged Gladiator's Sigil of Adaptation [Adapted]
        [219014] = { ids = {443099}, durs = {20} },  -- Vengeful Fire Spirit [Vengeful Fire Spirit]
        [219018] = { ids = {443238}, durs = {10} },  -- Esteemed Earthen Emblem [Esteemed Earthen Emblem]
        [219296] = { ids = {11790}, durs = {15} },  -- Entropic Skardyn Core [Poison Cloud]
        [219297] = { ids = {450610, 443381}, durs = {60, 15} },  -- Cinderbrew Stein [Cinderbrew Stein / Cinderbrew Stein]
        [219299] = { ids = {449490}, durs = {20} },  -- Synergistic Brewterializer [Synergistic Brewterializer]
        [219300] = { ids = {449792}, durs = {15} },  -- Skarmorak Shard [Crystalline Coalescense]
        [219305] = { ids = {451367}, durs = {15} },  -- Carved Blazikon Wax [Candle Comfort]
        [219307] = { ids = {451602}, durs = {15} },  -- Remnant of Darkness [Remnant of Darkness]
        [219311] = { ids = {450962}, durs = {10} },  -- Void Pactstone [Void Pactstone]
        [219312] = { ids = {449275}, durs = {20} },  -- Empowering Crystal of Anub'ikkaj [Nascent Empowerment]
        [219314] = { ids = {452146, 452229}, durs = {60, 8} },  -- Ara-Kara Sacbrood [Egg Sac / Spidersting]
        [219315] = { ids = {451779}, durs = {60} },  -- Refracting Aggression Module [Refracting Aggression Module]
        [219316] = { ids = {450969}, durs = {6} },  -- Ceaseless Swarmgland [Ceaseless Swarm]
        [219317] = { ids = {451303}, durs = {15} },  -- Harvester's Edict [Volatile Energy]
        [219318] = { ids = {446822}, durs = {30} },  -- Oppressive Orator's Larynx [Oppressive Orator's Larynx]
        [219321] = { ids = {452288}, durs = {20} },  -- Cirral Concoctory [Strand of the Lord]
        [219672] = { ids = {454560}, durs = {15} },  -- Darkmoon Deck: Radiance [Radiant Focus]
        [219932] = { ids = {345230}, durs = {20} },  -- Algari Competitor's Insignia of Alacrity [Gladiator's Insignia]
        [221233] = { ids = {449886, 449877}, durs = {8, 4} },  -- Deephunter's Bloody Hook [Deephunter's Bloody Hook / Deephunter's Bloody Hook]
        [221263] = { ids = {449895, 449892}, durs = {10, 9}, stack = 449892 },  -- Nerubian Venom-Tipped Dart [Predatory Instinct / Nerubian Venom-Tipped Dart]
        [221264] = { ids = {449753}, durs = {10} },  -- Fungarian Mystic's Cluster [Fungarian Mystic's Cluster]
        [221265] = { ids = {449710}, durs = {12} },  -- Charm of the Underground Beast [Charm of the Underground Beast]
        [222653] = { ids = {455536}, durs = {20}, stack = 455536 },  -- Darkmoon Deck: Symbiosis [Symbiosis]
        [222671] = { ids = {454978}, durs = {15} },  -- Darkmoon Deck: Vivacity [Vivacity of Light]
        [222680] = { ids = {457596}, durs = {15}, stack = 457596 },  -- Darkmoon Deck: Ascension [Lexicon of Mysteries]
        [224161] = { ids = {451748}, durs = {12} },  -- Stormrider Flight Badge [Stormrider Flight Badge]
        [225638] = { ids = {455420}, durs = {15} },  -- Spelunker's Waning Candle [Spelunker's Candle]
        [225651] = { ids = {455464}, durs = {30} },  -- Kaheti Shadeweaver's Emblem [Kaheti Shadeweaver's Dark Ritual]
        [225970] = { ids = {462159}, durs = {10} },  -- Nizrek's Holographic Manipulator [Terrible Visage]
        [226539] = { ids = {459228}, durs = {10}, stack = 459228 },  -- Scroll of Momentum [Full Momentum]
        [229493] = { ids = {345230}, durs = {20} },  -- Prized Aspirant's Insignia of Alacrity [Gladiator's Insignia]
        [229495] = { ids = {336139}, durs = {60} },  -- Prized Aspirant's Sigil of Adaptation [Adapted]
        [229781] = { ids = {345230}, durs = {20} },  -- Prized Gladiator's Insignia of Alacrity [Gladiator's Insignia]
        [229784] = { ids = {336139}, durs = {60} },  -- Prized Gladiator's Sigil of Adaptation [Adapted]
        [230026] = { ids = {472170, 472171, 466673, 472167}, durs = {30, 20, 15, 12} },  -- Scrapfield 9001 [Scrapfield 9001 Recharging / Scrapfield 9001 Recharging / Scrapfield Vortex / Scrapfield 9001 Overload]
        [230186] = { ids = {467251, 474467}, durs = {6, 1.5} },  -- Mister Pick-Me-Up [Mister Pick-Me-Up / Slightly Irradiated]
        [230192] = { ids = {474285}, durs = {15} },  -- Mug's Moxie Jug [Moxie Frenzy]
        [230199] = { ids = {1217427}, durs = {10} },  -- Zee's Thug Hotline [Call Thwack Jack]
        [230354] = { ids = {345230}, durs = {20} },  -- Astral Aspirant's Insignia of Alacrity [Gladiator's Insignia]
        [230356] = { ids = {336139}, durs = {60} },  -- Astral Aspirant's Sigil of Adaptation [Adapted]
        [230639] = { ids = {345230}, durs = {20} },  -- Astral Gladiator's Insignia of Alacrity [Gladiator's Insignia]
        [230642] = { ids = {336139}, durs = {60} },  -- Astral Gladiator's Sigil of Adaptation [Adapted]
        [230945] = { ids = {472360}, durs = {8} },  -- Wayward Vrykul's Lantern [Wayward Vrykul's Lantern]
        [231116] = { ids = {472228}, durs = {8} },  -- Cursed Pirate Skull [Cursed Pirate Skull]
        [232485] = { ids = {1214806}, durs = {10} },  -- Mechano-Core Amplifier [Mechano-Core Amplifier]
        [232541] = { ids = {1218713}, durs = {15} },  -- Improvised Seaforium Pacemaker [Explosive Adrenaline]
        [232545] = { ids = {1220413}, durs = {15} },  -- Gigazap's Zap-Cap [Turbo-Charged]
        [232883] = { ids = {472127, 472350}, durs = {5, 5} },  -- Turbo-Drain 5000 [Turbo-Drain 5000 / Turbo-Drain 5000]
        [232891] = { ids = {472184, 472185}, durs = {30, 30} },  -- Amorphous Relic [Miniature / Massive]
        [234185] = { ids = {1214057}, durs = {60} },  -- Dr. Scrapheal [Dr. Scrapheal]
        [234821] = { ids = {1215336}, durs = {10} },  -- Papa's Prized Putter [Papa Would Be Proud]
        [235283] = { ids = {1216424}, durs = {20} },  -- Bashful Book [Unpublished Steamy Romance Novel]
        [235363] = { ids = {1216650}, durs = {10} },  -- Suspicious Energy Drink [Suspicious Energy Drink]
        [235467] = { ids = {1216921}, durs = {15} },  -- Ominous Oil Residue [Ominous Oil Residue]
        [238386] = { ids = {1224918}, durs = {10} },  -- Void-Touched Fragment [Void-Touched Fragment]
        [238390] = { ids = {1225149, 1225151}, durs = {10, 10} },  -- Soulbreaker's Sigil [Soulbreaker's Sigil / Soulbreaker's Sigil]
        [240172] = { ids = {1231104}, durs = {12} },  -- Depleted K'areshi Battery [Depleted K'areshi Battery]
        [240213] = { ids = {1231221}, durs = {12} },  -- Veiling Mana Shroud [Veiling Mana Shroud]
        [240214] = { ids = {1231664}, durs = {20} },  -- Miniature Reshii Sandgarden [Disturbed Sands]
        [241340] = { ids = {60229}, durs = {15} },  -- Magister's Alchemist Stone [Strength]
        [242392] = { ids = {1239221}, durs = {15}, stack = 1239221 },  -- Diamantine Voidcore [Diamantine Voidcore]
        [242395] = { ids = {1239641}, durs = {10}, stack = 1239641 },  -- Astral Antenna [Astral Antenna]
        [242400] = { ids = {1240000}, durs = {12} },  -- Nexus-King's Command [Boon of the Oathsworn]
        [242404] = { ids = {1236691, 1236692}, durs = {480, 6} },  -- All-Devouring Nucleus [All-Devouring Nucleus / Void Reconstitution]
        [242497] = { ids = {1243843, 1243828}, durs = {30, 5} },  -- Azhiccaran Parapodia [Mite-y Feast / Azhiccaran Mite]
        [242867] = { ids = {1234025}, durs = {10} },  -- Automatic Footbomb Dispenser [Automatic Footbomb Dispenser]
        [245750] = { ids = {1244617}, durs = {15}, stack = 1244617 },  -- Darkmoon Deck: Void [Void Glass]
        [245752] = { ids = {345230}, durs = {20} },  -- Thalassian Competitor's Insignia of Alacrity [Gladiator's Insignia]
        [245829] = { ids = {1252487}, durs = {15} },  -- Darkmoon Deck: Hunt [Focused Hunt]
        [245846] = { ids = {1247411}, durs = {6}, stack = 1247411 },  -- Darkmoon Deck: Rot [Root Rot]
        [245855] = { ids = {1245025}, durs = {15} },  -- Darkmoon Deck: Blood [Farstrider's Guile]
        [246304] = { ids = {1252487}, durs = {15} },  -- Darkmoon Dominion: Hunt [Focused Hunt]
        [246305] = { ids = {1245025}, durs = {15} },  -- Darkmoon Dominion: Blood [Farstrider's Guile]
        [246306] = { ids = {1247411}, durs = {6}, stack = 1247411 },  -- Darkmoon Dominion: Rot [Root Rot]
        [246307] = { ids = {1244617}, durs = {15}, stack = 1244617 },  -- Darkmoon Dominion: Void [Void Glass]
        [246824] = { ids = {1246543, 1246545}, durs = {10, 10} },  -- Shadowguard's Twisted Harvester [Shadowguard's Twisted Harvester / Shadowguard's Twisted Harvester]
        [246939] = { ids = {1245376}, durs = {8}, stack = 1245376 },  -- Essence-Hunter's Eyeglass [Arcane Hunter]
        [246940] = { ids = {1245397}, durs = {15} },  -- Manaforged Aethercell [Manaforged Aethercell]
        [246941] = { ids = {1245431}, durs = {15} },  -- Symbiotic Ethergauze [Symbiotic Ethergauze]
        [246947] = { ids = {1247081, 1247511}, durs = {10, 5} },  -- Twisted Mana Sprite [Twisted Mana Sprite / Twisted Mana Sprite]
        [249341] = { ids = {1258534}, durs = {12}, stack = 1258534 },  -- Volatile Void Suffuser [Void Suffusion]
        [249342] = { ids = {1262753}, durs = {12} },  -- Heart of Ancient Hunger [Heart of Ancient Hunger]
        [249343] = { ids = {1266686, 1266687}, durs = {12, 12}, stack = 1266687 },  -- Gaze of the Alnseer [Alnsight / Alnscorned Essence]
        [249807] = { ids = {1264144}, durs = {6} },  -- The Eternal Egg [Eternal Eggshell]
        [249809] = { ids = {1259317}, durs = {10} },  -- Locus-Walker's Ribbon [Riftwalker's Temptation]
        [249810] = { ids = {1264337}, durs = {12} },  -- Shadow of the Empyrean Requiem [Empyrean Swiftness]
        [250214] = { ids = {1263762}, durs = {12} },  -- Lightspire Core [Radiant Light]
        [250223] = { ids = {1264613}, durs = {12} },  -- Soulcatcher's Charm [Echo of the Evercurse]
        [250224] = { ids = {1264404}, durs = {10} },  -- Mindpiercer's Sigil [Cosmic Siphon]
        [250227] = { ids = {1255816}, durs = {1} },  -- Kroluk's Warbanner [Kroluk's Warbanner]
        [250228] = { ids = {1254180}, durs = {30}, stack = 1254180 },  -- Resonant Bellowstone [Xathuux's Last Roar]
        [250229] = { ids = {1258223, 1258222}, durs = {15, 10} },  -- Idol of the War Loa [Nalorakk's Rage / Nalorakk's Rage]
        [250242] = { ids = {1254520, 1254514}, durs = {10, 5} },  -- Jelly Replicator [Gelatinous Protection / Coalesced Jelly]
        [250244] = { ids = {1260316, 1260321}, durs = {15, 10}, stack = 1260321 },  -- Permafrost Essence [Mark of Frost / Permafrost Reservoir]
        [250246] = { ids = {1254577}, durs = {12} },  -- Refueling Orb [Refueling Orb]
        [250248] = { ids = {1264294}, durs = {10} },  -- Mycolic Medicine [Glowcap Gift]
        [250253] = { ids = {1263447}, durs = {10} },  -- Whisper of the Duskwraith [Duskwraith's Infusion]
        [250256] = { ids = {1263318}, durs = {10} },  -- Heart of Wind [The Wind Awoken]
        [250258] = { ids = {1265566}, durs = {60} },  -- Vessel of Tortured Souls [A Restless Soul]
        [250259] = { ids = {1263077}, durs = {15} },  -- Sapling of the Dawnroot [Uprooted Lasher]
        [251782] = { ids = {1255226}, durs = {10} },  -- Withered Saptor's Paw [Withered Saptor's Paw]
        [251783] = { ids = {1266182}, durs = {30} },  -- Lost Idol of the Hash'ey [Bear]
        [251785] = { ids = {1266394, 1266403}, durs = {30, 15} },  -- Void-Reaper's Libram [Sacred Text / Sacred Duty]
        [251788] = { ids = {1259741, 1259228}, durs = {60, 10} },  -- Gift of Light [Gift of Light / Gift of Light]
        [251790] = { ids = {1265325}, durs = {10} },  -- Desecrated Chalice [Mire of Despair]
        [251792] = { ids = {1266299, 1266300}, durs = {15, 15} },  -- Glorious Crusader's Keepsake [Fanatical Inspiration / Fanatically Inspired]
        [251882] = { ids = {1283378}, durs = {15} },  -- Fragmented Light Shard [Blessing Light Shard]
        [251883] = { ids = {1253325}, durs = {10} },  -- Umbric's Channeling Focus [Looming Darkness]
        [252420] = { ids = {1255504}, durs = {10} },  -- Solarflare Prism [Solarflare Prism]
        [252956] = { ids = {1255460}, durs = {12} },  -- Aln-Bound Essence [Aln-Bound Essence]
        [252957] = { ids = {1255357, 1255367}, durs = {8, 8} },  -- Tangle of Vibrant Vines [Tangle of Vibrant Vines / Tangle of Vibrant Vines]
        [255328] = { ids = {345230}, durs = {20} },  -- Galactic Aspirant's Insignia of Alacrity [Gladiator's Insignia]
        [255330] = { ids = {336139}, durs = {60} },  -- Galactic Aspirant's Sigil of Adaptation [Adapted]
        [255614] = { ids = {345230}, durs = {20} },  -- Galactic Gladiator's Insignia of Alacrity [Gladiator's Insignia]
        [255617] = { ids = {336139}, durs = {60} },  -- Galactic Gladiator's Sigil of Adaptation [Adapted]
        [256326] = { ids = {1260522}, durs = {3} },  -- Fetid Dartfrog Idol [Fetid Dartfrog Idol]
        [259477] = { ids = {1265132}, durs = {18} },  -- Thriving Essence Sprig [Sapped Speed]
        [263282] = { ids = {1270343}, durs = {15} },  -- Repurposed Volatile Manacell [Volatile Power]
        [264507] = { ids = {1277482}, durs = {10} },  -- Crucible of Erratic Energies [Voidlust]
        [264878] = { ids = {1272698}, durs = {15} },  -- Astalor's Anguish Agitator [Agitated Anguish]
        [264968] = { ids = {1272942}, durs = {10} },  -- Telluric Leyblossom [Telluric Leyblossom]
        [265657] = { ids = {1276677}, durs = {15} },  -- Fiber of Living Agony [Fiber of Living Agony]
        [267469] = { ids = {345230}, durs = {20} },  -- Novice Combatant's Insignia of Alacrity [Gladiator's Insignia]
        [268292] = { ids = {1284698}, durs = {12} },  -- Sporelord's Mycelial Insignia [Sporelord's Mycelium]
        [270161] = { ids = {1305853}, durs = {60}, stack = 1305853 },  -- Fang of Umbral Malignance [Umbral Malignance]
        [270165] = { ids = {1295582}, durs = {12}, stack = 1295582 },  -- Keeper's Seething Core [Focus of Ula'tek]
        [270171] = { ids = {1305846}, durs = {30} },  -- Preternatural Antivenom [Preternatural Antivenom]
        [270174] = { ids = {1306823, 1306822, 1295649}, durs = {60, 15, 12} },  -- Idol of the Howling Nexus [Recovering Winds / Imminent Gale / Bolstering Gale]
        [270557] = { ids = {336139}, durs = {60} },  -- Venomous Aspirant's Sigil of Adaptation [Adapted]
        [270558] = { ids = {345230}, durs = {20} },  -- Venomous Aspirant's Insignia of Alacrity [Gladiator's Insignia]
        [270603] = { ids = {345230}, durs = {20} },  -- Venomous Gladiator's Insignia of Alacrity [Gladiator's Insignia]
        [270604] = { ids = {336139}, durs = {60} },  -- Venomous Gladiator's Sigil of Adaptation [Adapted]
        [273794] = { ids = {1295679}, durs = {15} },  -- Knot of Writhing Serpents [Writhing Venom]
        [273796] = { ids = {1295123}, durs = {15} },  -- Vile Vial of Volatile Venom [Debilitating Venom]
        [274493] = { ids = {1296714}, durs = {12} },  -- Effigy of Ula'tek's Faithful [Faith in Ula'tek]
        [274495] = { ids = {1296971, 1296976}, durs = {300, 12} },  -- Pulse Seeker's Oculus [Pulse Seeker's Oculus / Dilation]
        [274499] = { ids = {1296742}, durs = {8} },  -- Toxiferous Transfusion [Toxiferous Transfusion]
        [274892] = { ids = {345230}, durs = {20} },  -- Resilient Felblood Vial [Gladiator's Insignia]
        [274893] = { ids = {383168}, durs = {10} },  -- Frosty Klaxid Stinger [Azure Amplification]
        [280097] = { ids = {345230}, durs = {20} },  -- Venomous Aspirant's Insignia of Alacrity [Gladiator's Insignia]
    },

    stacks = {
        [230194] = 1216212,  -- Reverb Radio (Hyped)
        [230198] = 469889,  -- Eye of Kezan (Eye of Kezan)
        [242394] = 1240896,  -- Eradicating Arcanocore (Eradicating Arcanocore)
        [242401] = 1235879,  -- Brand of Ceaseless Ire (Infuriated)
        [270166] = 1303479,  -- Vashnik's Sanguine Rancor (Sanguine Rancor)
        [270167] = 1295057,  -- Wavecaller's Seastone (Tidal Insight)
    },
})

-- UNTRACKED equip-effect trinkets: damage/summon procs or flat passives -- no
-- player buff aura with a duration to display. The passive -> proc-spell link is
-- server-side (not in DB2). Listed for a possible future proc-ICD feature.
-- [212456] Void Reaper's Contract  (passive 444067 "Void Reaper's Contract") -- damage/summon proc (no buff aura)
-- [215173] Serum of Unconstrained Senses  (passive 438592 "Serum of Unconstrained Pleasure") -- damage/summon proc (no buff aura)
-- [219295] Sigil of Algari Concordance  (passive 443378 "Sigil of Algari Concordance") -- proc (no resolvable buff duration)
-- [219302] Scrapsinger's Symphony  (passive 443414 "Scrapsinger's Symphony") -- damage/summon proc (no buff aura)
-- [219304] Conductor's Wax Whistle  (passive 443525 "Candle Conductor's Whistle") -- damage/summon proc (no buff aura)
-- [225647] Shining Arathor Insignia  (passive 455432 "Shining Arathor Insignia") -- damage/summon proc (no buff aura)
-- [225648] Candle Confidant  (passive 455435 "Candle Confidant") -- damage/summon proc (no buff aura)
-- [225653] Siphoning Lightbrand  (passive 455446 "Siphoning Lightbrand") -- damage/summon proc (no buff aura)
-- [225657] Detachable Fang  (passive 455484 "Detachable Fang") -- damage/summon proc (no buff aura)
-- [225668] Unstable Power Suit Core  (passive 455436 "Unstable Power Suit Core") -- proc (no resolvable buff duration)
-- [225693] Shadowed Essence  (passive 455640 "Shadowed Essence") -- damage/summon proc (no buff aura)
-- [225891] Vile Vial of Kaheti Bile  (passive 456431 "Vile Vial of Kaheti Bile") -- proc (no resolvable buff duration)
-- [226521] Reinforced Wax Plating  (passive 459206 "Reinforced Wax Plating") -- damage/summon proc (no buff aura)
-- [231117] Darktide Wavebender's Orb  (passive 468034 "Darktide Wavebender's Orb") -- damage/summon proc (no buff aura)
-- [231118] Runecaster's Stormbound Rune  (passive 468033 "Runecaster's Stormbound Rune") -- damage/summon proc (no buff aura)
-- [238391] Arathi Minister's Receptacle  (passive 1223952 "Devout") -- unknown (empty description)
-- [242397] Sigil of the Cosmic Hunt  (passive 1235360 "Sigil of the Cosmic Hunt") -- damage/summon proc (no buff aura)
-- [242398] Naazindhri's Mystic Lash  (passive 1235387 "Naazindhri's Mystic Lash") -- damage/summon proc (no buff aura)
-- [242399] Screams of a Forgotten Sky  (passive 1235272 "Screams of a Forgotten Sky") -- damage/summon proc (no buff aura)
-- [242495] Incorporeal Warpclaw  (passive 1243118 "Incorporeal Warpclaw") -- damage/summon proc (no buff aura)
-- [246944] Mind-Fracturing Odium  (passive 1245148 "Mind-Fracturing Odium") -- proc (no resolvable buff duration)
-- [249805] Undreamt God's Oozing Vestige  (passive 1256790 "Undreamt God's Oozing Vestige") -- damage/summon proc (no buff aura)
-- [249811] Light of the Cosmic Crescendo  (passive 1258672 "Light of the Cosmic Crescendo") -- damage/summon proc (no buff aura)
-- [250241] Mark of Light  (passive 1250582 "Mark of Light") -- damage/summon proc (no buff aura)
-- [250245] Tumor of the Swarm  (passive 1250589 "Crawling Plague") -- damage/summon proc (no buff aura)
-- [250257] Eye of the Drowning Void  (passive 1250601 "Eye of the Drowning Void") -- damage/summon proc (no buff aura)
-- [251784] Sylvan Wakrapuku  (passive 1253112 "Sylvan Wakrapuku") -- damage/summon proc (no buff aura)
-- [251791] Holy Retributor's Order  (passive 1253119 "Holy Retributor's Order") -- damage/summon proc (no buff aura)
-- [251794] Gris-gris of Confidence  (passive 1253122 "Gris-gris of Confidence") -- proc (no resolvable buff duration)
-- [252677] Puzzling Crypt Relic  (passive 1283380 "Puzzling Crypt Relic") -- damage/summon proc (no buff aura)
-- [265027] Lucky Lynx Locket  (passive 1273106 "Lucky Lynx Locket") -- damage/summon proc (no buff aura)
-- [270163] Sszorak's Ferocity  (passive 1295617 "Sszorak's Ferocity") -- proc (no resolvable buff duration)
-- [270164] Gebbo's Bottomless Bag  (passive 1292291 "Gebbo's Bottomless Bag") -- proc (no resolvable buff duration)
-- [270173] Zul'jin's Guillotine Technique  (passive 1291728 "Guillotine") -- damage/summon proc (no buff aura)
-- [280123] Sharp Axe Holster  (passive 1307781 "Sharp Axe Holster") -- damage/summon proc (no buff aura)
